Repository BOINC/boinc, pull requests merged in 2018-10, with the labels that each got.

#2702 Drupal: Change user profile permissions
  drupal/sites/all/features/user_profiles/user_profiles.views_default.inc
  drupal/sites/default/boinc/modules/boincuser/boincuser.module
  drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
Labels: C: Web - Forums, C: Web - Project

#2710 [Android] Add Android Manager CI configuration
  .travis.yml
Labels: C: Android - Build

#2758 Manager, simple view: if project name not known yet, show URL
  clientgui/sg_ProjectPanel.cpp
Labels: C: Manager, C: Manager - Simple View, E: 1 day

#2778 [AppVeyor] Switch default build to Release x64
  appveyor.yml
  deploy/prepare_deployment.bat
Labels: C: Build System, P: Minor, T: Enhancement
