Repository BOINC/boinc, pull requests merged in 2018-06, with the labels that each got.

#2547 [WIP] [Manager] Add HTML TOU support to Wizard
  clientgui/TermsOfUsePage.cpp
  clientgui/TermsOfUsePage.h
  lib/gui_rpc_client.h
  lib/gui_rpc_client_ops.cpp
  lib/parse.cpp
Labels: C: Manager

#2558 Drupal: Added bts() functions to terms of use forms.
  drupal/sites/default/boinc/modules/boincuser/boincuser.module
  drupal/sites/default/boinc/modules/boincuser/includes/boincuser.forms.inc
Labels: C: Server - Other

#2559 Updated registration flow
  html/project.sample/project.inc
  html/user/download.php
  html/user/forum_forum.php
  html/user/forum_index.php
  html/user/join.php
  html/user/prefs.php
  html/user/sample_index.php
  html/user/welcome.php
Labels: C: Web - Forums, C: Web - Other, C: Web - Project
