Repository BOINC/boinc, pull requests merged in 2019-04, with the labels that each got.

#2800 client: throttling: only resume threads you suspended
  api/boinc_api.cpp
  lib/proc_control.cpp
Labels: C: Client - Daemon

#3062 Manager: add account manager functions to simple view
  clientgui/AdvancedFrame.cpp
  clientgui/AdvancedFrame.h
  clientgui/BOINCBaseFrame.cpp
  clientgui/BOINCBaseFrame.h
  clientgui/sg_BoincSimpleFrame.cpp
  clientgui/sg_BoincSimpleFrame.h
Labels: C: Manager - Simple View

#2732 [Manager] Fix project urls comparison
  client/gui_rpc_server_ops.cpp
  clientgui/ProjectInfoPage.cpp
Labels: C: Manager, P: Minor, T: Defect
