Repository BOINC/boinc, pull requests merged in 2020-08, with the labels that each got.

#3952 Added EVT_MENU_OPEN to the event table for Windows - Fixes #3934
  clientgui/AdvancedFrame.cpp
Labels: PR: Review required

#3955 script_validator: make scripts optional.
  sched/script_validator.cpp
Labels: PR: Review required

#3924 [Android] Use Okio to handle RPC.
  android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/RpcClient.java
Labels: C: Android - Manager, P: Minor, PR: Reviewed, T: Enhancement

#3870 exclude sysctl.h in linux
  configure.ac
Labels: C: Client - Build, P: Minor, PR: Reviewed, T: Enhancement

#3956 Mac: Automatically build Universal x86_64 / arm64 binaries
  client/app.h
  client/app_start.cpp
  client/cs_platforms.cpp
  client/hostinfo_unix.cpp
  clientgui/DlgAbout.cpp
  clientgui/mac/SetupSecurity.cpp
  clientgui/mac/config.h
  lib/mac/QBacktrace.c
  lib/mac/QCrashReport.c
  lib/mac/QMachOImage.c
  lib/mac/mac_backtrace.cpp
  mac_build/boinc.xcodeproj/project.pbxproj
  mac_build/buildFTGL.sh
  mac_build/buildWxMac.sh
  mac_build/buildc-ares.sh
  mac_build/buildcurl.sh
  mac_build/buildfreetype.sh
  mac_build/buildopenssl.sh
  mac_installer/release_boinc.sh
  mac_installer/release_brand.sh
Labels: PR: Review required

#3946 [Android] Remove warnings in compilation time.
  android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchProcessingActivity.kt
  android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
Labels: C: Android - Manager, P: Trivial, PR: Reviewed, T: Enhancement

#3979 Fix it will no throw an exception when the state == null.
  android/BOINC/app/src/main/java/edu/berkeley/boinc/client/Monitor.kt
Labels: C: Android - Manager, P: Trivial, PR: Reviewed, T: Enhancement

#3968 [Manager] Stopped shutdown client dialog from showing when told not to
  clientgui/AdvancedFrame.cpp
Labels: C: Manager, P: Minor, PR: Reviewed, T: Bugfix

#3954 Manager: clean up "Welcome page"
  3rdParty/vcpkg_ports/ports/rappture/CMakeLists.txt
  client/client_state.cpp
  client/gui_rpc_server_ops.cpp
  clientgui/AccountInfoPage.cpp
  clientgui/ProjectWelcomePage.cpp
  clientgui/WizardAttach.cpp
  clientsetup/win/CACreateProjectInitFile.cpp
  lib/gui_rpc_client_ops.cpp
  lib/project_init.cpp
  lib/project_init.h
  win_build/boinc_ss_vs2019.vcxproj
  win_build/boinccas_vs2019.vcxproj
  win_build/slide_show_vs2019.vcxproj
  win_build/uc2_graphics_vs2019.vcxproj
  win_build/wrappture_example_vs2019.vcxproj
Labels: PR: Review required

#3962 [VS2019] Fix VS2019 CI build cache
  appveyor.yml
  win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj
Labels: C: Build System, P: Trivial, T: Enhancement

#3990 Fix build after libexpat update on vcpkg
  3rdParty/vcpkg_ports/ports/rappture/CMakeLists.txt
Labels: C: Build System, P: Major, T: Bugfix

#3982 Manager: Add option to restore 'shutdown client' confirmation.
  clientgui/DlgOptions.cpp
  clientgui/DlgOptions.h
Labels: C: Manager, P: Minor, PR: Reviewed, T: Enhancement

#3716 configure.ac: Fix have_xss test to respect --without-x
  configure.ac
Labels: C: Client - Build, C: Client - Screen Saver, P: Minor, PR: Reviewed, T: Enhancement

#3967 [Android] Create a group of notifications for notices on Android Nougat and higher.
  android/BOINC/app/src/main/java/edu/berkeley/boinc/client/NoticeNotification.java
  android/BOINC/app/src/main/res/drawable/ic_boinc_notice.xml
  android/BOINC/app/src/main/res/mipmap-hdpi/ic_boinc_notice.png
  android/BOINC/app/src/main/res/mipmap-hdpi/ic_boinc_notice_white.png
  android/BOINC/app/src/main/res/mipmap-mdpi/ic_boinc_notice.png
  android/BOINC/app/src/main/res/mipmap-mdpi/ic_boinc_notice_white.png
  android/BOINC/app/src/main/res/mipmap-xhdpi/ic_boinc_notice.png
  android/BOINC/app/src/main/res/mipmap-xhdpi/ic_boinc_notice_white.png
  android/BOINC/app/src/main/res/mipmap-xxhdpi/ic_boinc_notice.png
  android/BOINC/app/src/main/res/mipmap-xxhdpi/ic_boinc_notice_white.png
  android/BOINC/app/src/main/res/mipmap-xxxhdpi/ic_boinc_notice.png
  android/BOINC/app/src/main/res/mipmap-xxxhdpi/ic_boinc_notice_white.png
Labels: C: Android - Manager, P: Minor, PR: Reviewed, T: Enhancement

#3987 [Android] Avoid potential memory usage problems.
  android/BOINC/app/build.gradle
  android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt
  android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCApplication.kt
  android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NoticesRecyclerViewAdapter.kt
  android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectControlsListAdapter.java
  android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/ProjectsListAdapter.java
  android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/TaskRecyclerViewAdapter.kt
  android/BOINC/app/src/main/java/edu/berkeley/boinc/attach/BatchConflictRecyclerViewAdapter.kt
  android/BOINC/app/src/main/java/edu/berkeley/boinc/utils/BOINCUtils.kt
  android/BOINC/app/src/main/res/drawable/ic_baseline_menu.xml
  android/BOINC/app/src/main/res/drawable/ic_baseline_menu_white.xml
Labels: C: Android - Manager, P: Minor, PR: Reviewed, T: Enhancement

#3994 [Android] Fix onNewIntent() warning in the event log.
  android/BOINC/app/src/main/java/edu/berkeley/boinc/BOINCActivity.kt
  android/BOINC/app/src/main/java/edu/berkeley/boinc/adapter/NavDrawerListAdapter.java
Labels: C: Android - Manager, P: Major, PR: Reviewed, T: Bugfix
