Repository BOINC/boinc, pull requests merged in 2021-10, with the labels that each got.

#4534 Fix a typo that introduced a bug
  clientgui/MainDocument.cpp
Labels: C: Manager, P: Trivial, T: Bugfix, PR: Review required

#4535 Mac: Build BOINC with wxWidgets 3.1.5
  clientgui/BOINCTaskBar.cpp
  clientgui/DlgExclusiveApps.cpp
  clientgui/mac/MacAccessiblity.mm
  clientgui/mac/MacBitmapComboBox.cpp
  clientgui/mac/MacBitmapComboBox.h
  clientgui/sg_BoincSimpleFrame.cpp
  clientgui/sg_ProjectPanel.cpp
  mac_build/HowToBuildBOINC_XCode.pdf
  mac_build/HowToBuildBOINC_XCode.rtf
  mac_build/boinc.xcodeproj/project.pbxproj
  mac_build/buildWxMac.sh
  mac_build/dependencyNames.sh
Labels: C: Manager, P: Major, T: Enhancement, C: Build System, PR: Reviewed

#4533 Remove semicolons in python code
  lib/submit_api.py
  py/Boinc/boincxml.py
  py/Boinc/sched_messages.py
  py/Boinc/setup_project.py
  samples/vm_wrapper/VMwrapper.py
  tests/old/test_1sec.py
  tests/old/test_uc.py
  tests/old/testbase.py
  tools/submit_api_test.py
Labels: C: Server - Other, P: Trivial, T: Enhancement, PR: Review required

#4540 Update ca-bundle.crt
  curl/ca-bundle.crt
Labels: P: Major, C: Client - Windows, T: Bugfix, PR: Review required

#4539 all master URL update to https:
  client/cs_scheduler.cpp
Labels: C: Client - Daemon, P: Minor, T: Enhancement, PR: Review required
