Repository BOINC/boinc, pull requests merged in 2022-01, with the labels that each got.

#4607 Fix gcc warnings
  client/dhrystone.cpp
  client/dhrystone.h
  client/whetstone.cpp
Labels: C: Client - Daemon, P: Trivial, T: Enhancement, PR: Reviewed

#4600 Add "Suspend when no mouse/keyboard input in last XX minutes" to local manager
  clientgui/DlgAdvPreferences.cpp
  clientgui/DlgAdvPreferencesBase.cpp
  clientgui/DlgAdvPreferencesBase.h
  lib/prefs.h
Labels: C: Manager, P: Minor, T: Enhancement, PR: Review required

#4051 [Android] Remove old sched method in client
  client/app_start.cpp
Labels: P: Trivial, T: Enhancement, C: Client - Android

#4154 Fix sah_select_bitness.m4
  m4/sah_select_bitness.m4
Labels: C: Client - Build, P: Minor, T: Bugfix, PR: Reviewed

#4608 Add flutter binaries cache
  .github/workflows/flutter-macos.yml
  .github/workflows/flutter-ubuntu.yml
  .github/workflows/flutter-windows.yml
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4611 [CI] Fix flutter cache
  .github/workflows/flutter-macos.yml
  .github/workflows/flutter-ubuntu.yml
  .github/workflows/flutter-windows.yml
Labels: P: Minor, C: Build System, T: Bugfix, PR: Reviewed

#4609 [Android] Parse project disk usage
  android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/Project.kt
  android/BOINC/app/src/main/java/edu/berkeley/boinc/rpc/ProjectsParser.kt
  android/BOINC/app/src/test/java/edu/berkeley/boinc/rpc/ProjectsParserTest.kt
Labels: C: Android - Manager, P: Minor, T: Enhancement, PR: Reviewed
