Repository BOINC/boinc, pull requests merged in 2022-04, with the labels that each got.

#4685 client: Fixes for new version check
  client/client_state.cpp
  client/current_version.cpp
  client/current_version.h
  client/main.cpp
Labels: C: Client - Daemon, P: Major, C: Client - Macintosh, T: Bugfix, PR: Reviewed

#4687 Fix Xcode 13 (Apple clang version 13.1.6) compiler warnings
  client/check_security.cpp
  clientgui/mac/SetVersion.cpp
  clientgui/mac/SetupSecurity.cpp
  clientscr/gfx_cleanup.mm
  clientscr/mac_saver_module.cpp
  lib/mac/QBacktrace.c
  lib/mac/QCrashReport.c
  lib/mac/QMachOImage.c
  lib/mac/QSymbols.c
  lib/mac/QTaskMemory.c
  lib/mac/mac_backtrace.cpp
  lib/mac/mac_spawn.cpp
  mac_build/boinc.xcodeproj/project.pbxproj
  mac_installer/AddRemoveUser.cpp
  mac_installer/Installer.cpp
  mac_installer/PostInstall.cpp
  mac_installer/finish_install.cpp
  mac_installer/uninstall.cpp
Labels: C: Client - Build, P: Trivial, T: Enhancement, C: Installer - Macintosh, C: Client - Macintosh, PR: Reviewed

#4692 bump wrapper and vboxwrapper version #s
  version.h
  win_build/vboxwrapper.vcxproj
  win_build/vboxwrapper_vs2013.vcxproj
  win_build/vboxwrapper_vs2019.vcxproj
  win_build/wrapper.vcxproj
  win_build/wrapper_vs2013.vcxproj
  win_build/wrapper_vs2019.vcxproj
Labels: P: Trivial, T: Enhancement, C: Apps - VboxWrapper, C: Apps - Wrapper, PR: Reviewed

#4691 [CI] Fix mingw-vcpkg build
  mingw/ci_make_apps.sh
Labels: P: Major, C: Build System, T: Bugfix, PR: Review required

#4698 Update vboxwrapper and wrapper versions in configure.ac file
  configure.ac
Labels: P: Trivial, C: Apps - VboxWrapper, C: Apps - Wrapper, T: Bugfix, PR: Reviewed

#4700 [windows][cmake][ci] Add windows libs cmake
  .github/workflows/windows.yml
  linux/ci_configure_libs_cmake.sh
  windows/bootstrap_vcpkg_cmake.bat
  windows/ci_build_libs_cmake.bat
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4705 [Linux][vcpkg][manifests] vcpkg Linux in manifests mode
  linux/update_vcpkg_apps.sh
  linux/update_vcpkg_client.sh
  linux/update_vcpkg_libs.sh
  linux/vcpkg_config_apps/vcpkg.json
  linux/vcpkg_config_client/vcpkg.json
  linux/vcpkg_config_libs/vcpkg.json
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4706 [Mingw][vcpkg][manifests] mingw vcpkg manifests mode
  linux/update_vcpkg_apps.sh
  linux/update_vcpkg_client.sh
  linux/update_vcpkg_libs.sh
  mingw/update_vcpkg.sh
  mingw/vcpkg_config_apps/vcpkg.json
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4708 [Windows][vcpkg][CI] Add windows msbuild manifests mode
  win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj
  win_build/vcpkg_config_msbuild_ARM64/vcpkg.json
  win_build/vcpkg_config_msbuild_x64/vcpkg.json
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4711 Remove unused variable in GLOBAL_PREFS.
  lib/prefs.h
Labels: P: Trivial, T: Enhancement, C: Library, PR: Reviewed

#4710 [MinGW][cmake] Add cmake libs in mingw
  .github/workflows/mingw.yml
  mingw/bootstrap_vcpkg_cmake.sh
  mingw/ci_configure_libs_cmake.sh
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4713 [Android][cmake] Add android libs cmake
  .github/workflows/android.yml
  .gitignore
  android/bootstrap_vcpkg_cmake.sh
  android/buildAndroidBOINC-CI.sh
  android/ci_build_libs_cmake.sh
  android/ndk_common.sh
  lib/vcpkg_config_android/vcpkg.json
Labels: P: Trivial, T: Enhancement, C: Android - Build, PR: Reviewed

#4385 [Linux][Manager][Scripts] Compile linux manager with vcpkg
  .github/workflows/linux.yml
  deploy/prepare_deployment.py
  linux/ci_configure_manager.sh
  linux/update_vcpkg_manager.sh
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4718 [osx][cmake] Add osx libs cmake
  .github/workflows/osx.yml
  3rdParty/vcpkg_ports/triplets/ci/arm64-osx.cmake
  3rdParty/vcpkg_ports/triplets/ci/x64-osx.cmake
  osx/bootstrap_vcpkg_cmake.sh
  osx/ci_build_libs_cmake.sh
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4723 Fix bug in python DB code
  py/Boinc/db_base.py
Labels: C: Server - Other, P: Trivial, T: Bugfix, PR: Reviewed

#4722 Remote job submission: clean up permissions checking
  html/inc/submit_util.inc
  html/user/job_file.php
  html/user/sandbox.php
  html/user/submit.php
  html/user/submit_rpc_handler.php
Labels: C: Server - Documentation, P: Trivial, T: Enhancement, C: Server - Remote Submission, PR: Reviewed

#4724 [CI][vcpkgl][Apps] Linux apps compile gui with vcpkg
  linux/vcpkg_config_apps/vcpkg.json
  samples/Makefile.am
  samples/example_app/Makefile
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4729 Mac: Add new exit message for OS 10.5 Catalina or newer
  clientgui/DlgExitMessage.cpp
Labels: C: Manager, P: Trivial, T: Enhancement, PR: Reviewed

#4734 Remove outdated files
  .gitignore
  boinc_vs2010.sln.ci.patch
  client/test_fx_in
  client/test_fx_out
  client/test_fx_out1
  clientscr/progress/win/x64/boincscr.exe
  clientscr/progress/win/x86/boincscr.exe
  samples/example_app/bin/22489/i686-apple-darwin/Helvetica.txf
  samples/example_app/bin/22489/i686-apple-darwin/example_app_22489_i686-apple-darwin
  samples/example_app/bin/22489/i686-apple-darwin/example_app_graphics_22489_i686-apple-darwin
  samples/example_app/bin/22489/i686-apple-darwin/logo.jpg
  samples/example_app/bin/22489/i686-apple-darwin/version.xml
  samples/example_app/bin/22489/i686-pc-linux-gnu/Helvetica.txf
  samples/example_app/bin/22489/i686-pc-linux-gnu/example_app_22489_i686-pc-linux-gnu
  samples/example_app/bin/22489/i686-pc-linux-gnu/example_app_graphics_22489_i686-pc-linux-gnu
  samples/example_app/bin/22489/i686-pc-linux-gnu/logo.jpg
  samples/example_app/bin/22489/i686-pc-linux-gnu/version.xml
  samples/example_app/bin/22489/windows_intelx86/Helvetica.txf
  samples/example_app/bin/22489/windows_intelx86/example_app_22489_windows_intelx86.exe
  samples/example_app/bin/22489/windows_intelx86/example_app_graphics_22489_windows_intelx86.exe
  samples/example_app/bin/22489/windows_intelx86/logo.jpg
  samples/example_app/bin/22489/windows_intelx86/version.xml
  samples/example_app/bin/22489/windows_x86_64/Helvetica.txf
  samples/example_app/bin/22489/windows_x86_64/example_app_22489_windows_x86_64.exe
  samples/example_app/bin/22489/windows_x86_64/example_app_graphics_22489_windows_x86_64.exe
  samples/example_app/bin/22489/windows_x86_64/logo.jpg
  samples/example_app/bin/22489/windows_x86_64/version.xml
  samples/example_app/bin/22489/x86_64-apple-darwin/Helvetica.txf
  samples/example_app/bin/22489/x86_64-apple-darwin/example_app_22489_x86_64-apple-darwin
  samples/example_app/bin/22489/x86_64-apple-darwin/example_app_graphics_22489_x86_64-apple-darwin
  samples/example_app/bin/22489/x86_64-apple-darwin/logo.jpg
  samples/example_app/bin/22489/x86_64-apple-darwin/version.xml
  samples/example_app/bin/22489/x86_64-pc-linux-gnu/Helvetica.txf
  samples/example_app/bin/22489/x86_64-pc-linux-gnu/example_app_22489_x86_64-pc-linux-gnu
  samples/example_app/bin/22489/x86_64-pc-linux-gnu/example_app_graphics_22489_x86_64-pc-linux-gnu
  samples/example_app/bin/22489/x86_64-pc-linux-gnu/logo.jpg
  samples/example_app/bin/22489/x86_64-pc-linux-gnu/version.xml
  samples/example_app/bin/24253/windows_intelx86/example_app_24253_windows_intelx86.exe
  win_build/installerv2/BOINC.ism
  win_build/installerv2/BOINC_vbox.ism
  win_build/installerv2/BOINCx64.ism
  win_build/installerv2/BOINCx64_vbox.ism
  win_build/installerv2/redist/Windows/Win32/boinccas.dll
  win_build/installerv2/redist/Windows/x64/boinccas.dll
Labels: C: Undetermined, P: Trivial, T: Enhancement, PR: Review required

#4735 Mac installer: Remove old screensaver used only for MacOS < OS10.8
  clientgui/sg_ProjectPanel.cpp
  clientscr/BOINCSaver_MacOS10_6_7.zip
  mac_installer/PostInstall.cpp
  mac_installer/release_boinc.sh
  mac_installer/release_brand.sh
Labels: P: Trivial, T: Enhancement, C: Installer - Macintosh, PR: Reviewed
