Repository BOINC/boinc, pull requests merged in 2022-06, with the labels that each got.

#4758 [Bugfix] Fix version util and files
  set-vboxwrapper-version.py
  set-version.py
  set-wrapper-version.py
  win_build/installerv2/BOINCx64.ism
  win_build/installerv2/BOINCx64_vbox.ism
  win_build/wrapper.vcxproj
  win_build/wrapper_vs2013.vcxproj
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4760 [Manager] Compile manager with new libwebkit2gtk lib for newer unbuntu
  .github/workflows/linux.yml
  3rdParty/buildLinuxDependencies.sh
Labels: C: Client - Build, P: Trivial, T: Enhancement, PR: Reviewed

#4759 [vcpkg] Unify manifests vcpkg files
  3rdParty/vcpkg_ports/configs/apps/android/vcpkg.json
  3rdParty/vcpkg_ports/configs/apps/linux/vcpkg.json
  3rdParty/vcpkg_ports/configs/apps/mingw/vcpkg.json
  3rdParty/vcpkg_ports/configs/client/vcpkg.json
  3rdParty/vcpkg_ports/configs/libs/vcpkg.json
  3rdParty/vcpkg_ports/configs/libs/windows/vcpkg.json
  3rdParty/vcpkg_ports/configs/msbuild/ARM64/vcpkg.json
  3rdParty/vcpkg_ports/configs/msbuild/x64/vcpkg.json
  android/buildAndroidBOINC-CI.sh
  android/ci_build_libs_cmake.sh
  android/vcpkg_config_client/vcpkg.json
  lib/CMakeLists.txt
  lib/vcpkg.json
  linux/ci_configure_libs_cmake.sh
  linux/update_vcpkg_apps.sh
  linux/update_vcpkg_client.sh
  linux/update_vcpkg_libs.sh
  mingw/ci_configure_libs_cmake.sh
  mingw/update_vcpkg.sh
  osx/ci_build_libs_cmake.sh
  set-version.py
  win_build/boinc.props
  win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj
  windows/ci_build_libs_cmake.bat
Labels: C: Client - Build, P: Trivial, T: Enhancement, C: Android - Build, C: Build System, PR: Reviewed

#4757 Client: use cuDeviceTotalMem_v2() if available to get >4GB mem size for NVIDIA GPUs
  client/gpu_nvidia.cpp
Labels: P: Minor, T: Enhancement, C: Client - Linux, PR: Reviewed

#4764 [bugfix] Add webkit2gtk ld flags
  m4/boinc_wxwidgets.m4
Labels: C: Client - Build, P: Minor, T: Bugfix, PR: Reviewed

#4765 make_project: Removed dependency of long gone files causing "failed to copy" warnings
  py/Boinc/setup_project.py
Labels: C: Server - Setup, P: Minor, T: Bugfix, PR: Reviewed

#4767 Update for Xcode 13: Mac VBoxWrapper build script & Xcode project
  samples/vboxwrapper/BuildMacVboxWrapper.sh
  samples/vboxwrapper/vboxwrapper.xcodeproj/project.pbxproj
Labels: P: Minor, T: Enhancement, C: Build System, PR: Reviewed

#4769 [web] fix deprecated passing null to parameter of type string.
  html/inc/boinc_db.inc
Labels: C: Web - Project, P: Trivial, T: Bugfix

#4770 Web: fix some PHP 8 deprecation warnings
  html/inc/boinc_db.inc
  html/inc/user.inc
  html/inc/util.inc
  html/inc/util_basic.inc
  html/user/server_status.php
  html/user/validate_email_addr.php
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed

#4774 Web: various changes to remove PHP 8.1 warnings and errors
  html/inc/bootstrap.inc
  html/inc/db_ops.inc
  html/inc/host.inc
  html/inc/team.inc
  html/inc/user.inc
  html/inc/util_basic.inc
  html/ops/db_action.php
  html/ops/mass_email.php
  html/user/cert1.php
  html/user/cert_all.php
  html/user/cert_team.php
  html/user/forum_post.php
Labels: C: Web - Project, P: Major, T: Bugfix, PR: Reviewed

#4777 web: a couple more PHP 8.1 fixes
  html/inc/user.inc
  html/inc/util.inc
Labels: C: Web - Project, P: Major, T: Bugfix

#4775 [Wasm] Compile wasm with html
  .gitignore
  Makefile.am
  configure.ac
  deploy/prepare_deployment.py
  samples/wasm/index.html
Labels: C: Client - Build, P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4778 web: a couple more PHP 8.1 fixes
  html/inc/user.inc
  html/inc/util.inc
Labels: C: Web - Project, P: Major, T: Bugfix

#4785 [Manager] Create proper sizing on SimpleView
  clientgui/sg_BoincSimpleFrame.cpp
  clientgui/sg_BoincSimpleFrame.h
Labels: C: Manager, P: Major, C: Manager - Simple View, T: Bugfix, PR: Review required

#4792 [Windows] Remove vcpkg cache miss error workaround
  win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4791 [wasm] Add debug information
  .github/workflows/wasm.yml
  wasm/ci_configure_client.sh
Labels: P: Minor, C: Build System, PR: Reviewed, C: Client - WASM

#4794 PHP 8.1 fixes
  html/ops/build_po.php
  html/ops/delete_spammers.php
  html/ops/team_import.php
Labels: C: Web - Project, P: Major, T: Enhancement, PR: Reviewed

#4796 [vcpkg] wxwidgets vcpkg fix
  linux/ci_configure_manager.sh
Labels: P: Major, C: Build System, T: Bugfix, PR: Reviewed

#4799 Tweak Bolt and Bossa to make them work again
  html/inc/bolt_db.inc
  html/inc/bossa_db.inc
  html/inc/bossa_example.inc
Labels: C: Web - Project, P: Minor, T: Bugfix

#4797 [Linux][Manger][vcpkg] Set webkit2gtk-4.0 ldflags only for wxwidgets vcpkg manager.
  linux/ci_configure_manager.sh
  m4/boinc_wxwidgets.m4
Labels: P: Minor, C: Build System, T: Bugfix, PR: Reviewed

#4803 client: ignore case in project lookup by URL
  client/client_state.cpp
Labels: C: Client - Daemon, P: Trivial, T: Bugfix, PR: Reviewed

#4795 [wasm] Disable get mac address in wasm.
  client/hostinfo_network.cpp
Labels: P: Minor, T: Enhancement, PR: Reviewed, C: Client - WASM

#4805 build fcgi_file_upload_handler w/o mysql libs
  Makefile.incl
  sched/Makefile.am
Labels: P: Minor, T: Enhancement, C: Server - Remote Submission

#4800 client: if project has zero resource share AND work buf min is zero, don't fetch from it unless device instance is actually idle.
  client/work_fetch.cpp
Labels: C: Client - Scheduler Policy, P: Major, T: Bugfix, PR: Reviewed

#4808 [Windows][Manager] Do proper verifications when saving state on application exit
  clientgui/ViewWork.cpp
Labels: C: Manager, P: Major, T: Bugfix, PR: Reviewed

#4813 [Android][CI] Fix android ANDROID_NDK_ROOT environment variable in CI
  .github/workflows/android.yml
Labels: P: Major, C: Build System, T: Bugfix, PR: Reviewed

#4814 [CI] Single job on PRs only
  .github/workflows/android.yml
  .github/workflows/flutter-macos.yml
  .github/workflows/flutter-ubuntu.yml
  .github/workflows/flutter-windows.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/source-code-check.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#4812 [CI] Add to deploy logs, locale and skins
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
  deploy/prepare_deployment.py
Labels: P: Minor, T: Enhancement, C: Build System, PR: Reviewed

#4811 [Manager][linux] Search for skins in /usr/(local)/share/boinc-manager/skins or ./skins folders.
  Makefile.am
  clientgui/SkinManager.cpp
  clientgui/skins/Makefile.am
  configure.ac
Labels: P: Minor, C: Manager - Simple View, T: Bugfix, PR: Review required
