Repository BOINC/boinc, pull requests merged in 2023-12, with the labels that each got.

#5442 web: fix PHP warning in login action.
  html/user/login_action.php
  sched/file_upload_handler.cpp
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed

#5443 Eliminate some PHP warnings.
  html/inc/boinc_db.inc
  html/inc/prefs_util.inc
  html/user/login_form.php
  html/user/notices.php
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed

#5439 Fix bad data in Diskwhen client disconnects
  clientgui/ViewResources.cpp
Labels: C: Manager, P: Trivial, T: Bugfix, PR: Reviewed

#5449 Code reorganization and cleanup. No functional changes.
  samples/vboxwrapper/Makefile
  samples/vboxwrapper/vbox_common.cpp
  samples/vboxwrapper/vbox_common.h
  samples/vboxwrapper/vbox_vboxmanage.cpp
  samples/vboxwrapper/vbox_vboxmanage.h
  samples/vboxwrapper/vboxcheckpoint.h
  samples/vboxwrapper/vboxjob.h
  samples/vboxwrapper/vboxwrapper.cpp
  samples/vboxwrapper/vboxwrapper.h
Labels: P: Trivial, T: Enhancement, C: Apps - VboxWrapper, PR: Reviewed

#5448 Windows: add AVX512 support
  client/hostinfo_win.cpp
Labels: P: Major, T: Enhancement, C: Client - Windows, PR: Reviewed

#5450 [CI] Build wrapper and vboxwrapper on CI for release
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  linux/arm64/build_curl_arm64.sh
  linux/arm64/build_example_arm64.sh
  linux/arm64/build_libraries_arm64.sh
  linux/arm64/build_openssl_arm64.sh
  remove-pkg-config.patch
  samples/condor/Makefile
  samples/example_app/Makefile
  samples/multi_thread/Makefile
  samples/nvcuda/common.mk
  samples/nvcuda/common_mac.mk
  samples/sleeper/Makefile
  samples/sporadic/Makefile
  samples/vboxmonitor/Makefile
  samples/vboxwrapper/Makefile
  samples/wrapper/Makefile
  samples/wrappture/Makefile
Labels: P: Trivial, T: Enhancement, C: Build System

#5460 Fix CI
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  3rdParty/vcpkg_ports/ports/libsystemd/pkgconfig.patch
  3rdParty/vcpkg_ports/ports/libsystemd/portfile.cmake
  3rdParty/vcpkg_ports/ports/libsystemd/vcpkg.json
  snap/snapcraft.yaml
Labels: P: Major, C: Build System, T: Bugfix

#5459 fix PHP8 deprecations in admin web
  html/ops/dbinfo.php
Labels: C: Web - Project, P: Minor, T: Bugfix

#5464 Remove custom libsystemd vcpkg port that was updated on upstream
  3rdParty/vcpkg_ports/ports/libsystemd/pkgconfig.patch
  3rdParty/vcpkg_ports/ports/libsystemd/portfile.cmake
  3rdParty/vcpkg_ports/ports/libsystemd/vcpkg.json
Labels: P: Trivial, T: Enhancement, C: Build System

#5458 vboxwrapper: add the ability to share project and slot directories
  .github/workflows/linux.yml
  client/app_start.cpp
  configure.ac
  deploy/prepare_deployment.py
  lib/win_util.cpp
  lib/win_util.h
  samples/Makefile.am
  samples/vboxwrapper/Makefile
  samples/vboxwrapper/boinc_resolve_1
  samples/vboxwrapper/vbox_common.cpp
  samples/vboxwrapper/vbox_common.h
  samples/vboxwrapper/vbox_vboxmanage.cpp
  samples/vboxwrapper/vboxjob.cpp
  samples/vboxwrapper/vboxjob.h
  samples/vboxwrapper/vboxwrapper.cpp
  samples/vboxwrapper/vboxwrapper.h
  samples/worker/Makefile
  samples/worker/worker.cpp
  samples/worker/worker_vm_in
  samples/worker/worker_vm_out
  samples/wrapper/Makefile
  set-vboxwrapper-version.py
  set-worker-version.py
  set-wrapper-version.py
  tools/backend_lib.h
  tools/update_versions
  version.h
  win_build/vboxwrapper.vcxproj
  win_build/worker.vcxproj
Labels: P: Major, T: Enhancement, C: Apps - VboxWrapper, C: Apps - Wrapper, C: Build System, PR: Reviewed

#5466 Fix source code check by excluding ODP file extension
  ci_tools/source_code_check.py
  ci_tools/trailing_whitespaces_check.py
Labels: P: Trivial, C: Build System, T: Bugfix

#5465 Add linux packaging testing CI
  .github/workflows/debrepo/Dockerfile
  .github/workflows/linux-package.yml
  .github/workflows/rpmrepo/Dockerfile.fedora
  .github/workflows/rpmrepo/Dockerfile.suse
  tests/linux_package_tests/integration_tests.py
Labels: P: Minor, T: Enhancement, C: Build System

#5469 Add some files (in samples/) that are needed to run the example apps as VM apps.
  samples/vboxwrapper/boinc_resolve
  samples/worker/run_worker_1.sh
  samples/worker/vbox_job_1.xml
  samples/worker/vm_version.xml
Labels: P: Trivial, T: Enhancement, C: Apps - VboxWrapper, PR: Reviewed

#5468 fix some spurious server warning messages
  html/user/notices.php
  sched/file_upload_handler.cpp
Labels: C: Web - Project, P: Trivial, T: Enhancement, PR: Reviewed

#5470 web: fix some PHP8 warnings
  html/inc/boinc_db.inc
  html/inc/user.inc
  html/inc/util.inc
  html/inc/xml.inc
  html/user/server_status.php
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed

#5472 demo_submit, demo_query: allow > 1 input and output files
  sched/sample_assimilator.cpp
  tools/demo_query
  tools/demo_submit
Labels: C: Server - Other, P: Trivial, T: Enhancement, PR: Reviewed

#5471 Fix android build
  3rdParty/vcpkg_ports/ports/openssl/asm-comments.patch
  3rdParty/vcpkg_ports/ports/openssl/declspec-align.patch
  3rdParty/vcpkg_ports/ports/openssl/install-pc-files.cmake
  3rdParty/vcpkg_ports/ports/openssl/openssl.pc.in
  3rdParty/vcpkg_ports/ports/openssl/portfile.cmake
  3rdParty/vcpkg_ports/ports/openssl/qt-msvc.patch
  3rdParty/vcpkg_ports/ports/openssl/script-prefix.patch
  3rdParty/vcpkg_ports/ports/openssl/unix/android-cc.patch
  3rdParty/vcpkg_ports/ports/openssl/unix/configure
  3rdParty/vcpkg_ports/ports/openssl/unix/disable-quicserver.patch
  3rdParty/vcpkg_ports/ports/openssl/unix/move-openssldir.patch
  3rdParty/vcpkg_ports/ports/openssl/unix/no-empty-dirs.patch
  3rdParty/vcpkg_ports/ports/openssl/unix/no-static-libs-for-shared.patch
  3rdParty/vcpkg_ports/ports/openssl/unix/portfile.cmake
  3rdParty/vcpkg_ports/ports/openssl/unix/remove-deps.cmake
  3rdParty/vcpkg_ports/ports/openssl/usage
  3rdParty/vcpkg_ports/ports/openssl/vcpkg-cmake-wrapper.cmake.in
  3rdParty/vcpkg_ports/ports/openssl/vcpkg.json
  3rdParty/vcpkg_ports/ports/openssl/windows/install-layout.patch
  3rdParty/vcpkg_ports/ports/openssl/windows/install-pdbs.patch
  3rdParty/vcpkg_ports/ports/openssl/windows/portfile.cmake
  3rdParty/vcpkg_ports/triplets/default/arm-android.cmake
  3rdParty/vcpkg_ports/triplets/default/arm-neon-android.cmake
  3rdParty/vcpkg_ports/triplets/default/armv6-android.cmake
  3rdParty/vcpkg_ports/triplets/default/x86-android.cmake
  ci_tools/source_code_check.py
  ci_tools/trailing_whitespaces_check.py
Labels: P: Blocker, C: Build System, T: Bugfix

#5473 [CI] Optimize vcpkg openssl build fix
  3rdParty/vcpkg_ports/ports/openssl/unix/disable-quicserver.patch
  3rdParty/vcpkg_ports/ports/openssl/unix/portfile.cmake
Labels: P: Trivial, T: Enhancement, C: Build System

#5474 [CI] Simplify build, remove custom openssl vcpkg port
  3rdParty/vcpkg_ports/configs/apps/android/vcpkg.json
  3rdParty/vcpkg_ports/configs/apps/linux/vcpkg.json
  3rdParty/vcpkg_ports/configs/apps/mingw/vcpkg.json
  3rdParty/vcpkg_ports/configs/client/vcpkg.json
  3rdParty/vcpkg_ports/configs/client/wasm/vcpkg.json
  3rdParty/vcpkg_ports/configs/libs/vcpkg.json
  3rdParty/vcpkg_ports/configs/libs/windows/vcpkg.json
  3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
  3rdParty/vcpkg_ports/configs/msbuild/ARM64/vcpkg.json
  3rdParty/vcpkg_ports/configs/msbuild/x64/vcpkg.json
  3rdParty/vcpkg_ports/ports/openssl/unix/disable-quicserver.patch
  3rdParty/vcpkg_ports/ports/openssl/unix/portfile.cmake
Labels: T: Enhancement, C: Build System

#5475 Fix some PHP8 warnings
  html/inc/util.inc
  html/user/am_set_info.php
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed
