Repository BOINC/boinc, pull requests merged in 2023-06, with the labels that each got.

#5260 web: job-submission tweaks
  html/inc/dir_hier.inc
  html/inc/sandbox.inc
  html/user/manage_app.php
  html/user/sandbox.php
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed

#5261 client: if sched request fails, show the scheduler URL (that might be the problem)
  client/scheduler_op.cpp
Labels: C: Client - Daemon, P: Trivial, T: Enhancement, PR: Reviewed

#5270 [Client] Add alert if idle time to resume computing is greater than idle time to suspend computing
  client/cs_prefs.cpp
Labels: C: Client - Daemon, P: Minor, T: Enhancement, PR: Review required

#5257 client: avoid overscheduling CPUs in presence of MT jobs
  client/cpu_sched.cpp
  client/result.h
  client/rr_sim.cpp
  client/sim.cpp
  client/sim_util.cpp
Labels: C: Client - Scheduler Policy, T: Bugfix, PR: Review required

#5269 Manager, computing prefs dialog: Fix bug where the "In use means..." value mysteriously showed up in the "suspend when non-BOINC..." field.
  clientgui/DlgAdvPreferences.cpp
Labels: C: Manager, P: Major, T: Bugfix, PR: Reviewed

#5267 Mac: Support Dark Mode in Advanced View
  clientgui/AdvancedFrame.cpp
  clientgui/AdvancedFrame.h
  clientgui/BOINCBaseFrame.cpp
  clientgui/BOINCBaseFrame.h
  clientgui/BOINCBaseView.cpp
  clientgui/BOINCBaseView.h
  clientgui/BOINCGUIApp.cpp
  clientgui/BOINCGUIApp.h
  clientgui/BOINCListCtrl.cpp
  clientgui/BOINCListCtrl.h
  clientgui/NoticeListCtrl.cpp
  clientgui/NoticeListCtrl.h
  clientgui/SkinManager.cpp
  clientgui/SkinManager.h
  clientgui/ViewResources.cpp
  clientgui/ViewResources.h
  clientgui/ViewStatistics.cpp
  clientgui/ViewStatistics.h
  clientgui/common/wxPieCtrl.cpp
  clientgui/mac/MacBitmapComboBox.h
  clientgui/mac/templates/Info.plist
  clientgui/sg_BoincSimpleFrame.cpp
  clientgui/sg_BoincSimpleFrame.h
  clientgui/sg_DlgMessages.cpp
  clientgui/sg_DlgMessages.h
  clientgui/sg_DlgPreferences.cpp
  clientgui/sg_DlgPreferences.h
  clientgui/sg_PanelBase.cpp
  clientgui/sg_PanelBase.h
  clientgui/sg_ProjectPanel.cpp
  clientgui/sg_ProjectPanel.h
  clientgui/sg_TaskPanel.cpp
  clientgui/sg_TaskPanel.h
Labels: C: Manager, P: Minor, T: Enhancement, C: Manager - Simple View, PR: Reviewed

#5279 Mac: Use strtod_l() only in Manager. Use strtod() in client, etc.
  lib/parse.cpp
  lib/parse.h
  mac_build/boinc.xcodeproj/project.pbxproj
Labels: P: Minor, T: Enhancement, C: Client - Macintosh, PR: Reviewed

#5282 Web: add "download as PNG" button to certificates.
  html/inc/cert.inc
  html/inc/user.inc
  html/user/cert1.php
  html/user/cert_all.php
  html/user/cert_team.php
  html/user/html2canvas.min.js
Labels: C: Web - Project, P: Trivial, T: Enhancement, PR: Reviewed

#5264 DEB repository workflow
  .github/workflows/deb-package.yml
  .github/workflows/debrepo/Dockerfile
  .github/workflows/debrepo/aptly.bullseye.conf
  .github/workflows/debrepo/aptly.buster.conf
  .github/workflows/debrepo/aptly.focal.conf
  .github/workflows/debrepo/aptly.jammy.conf
  .github/workflows/debrepo/package_depends.sh
  .github/workflows/debrepo/package_prepare.sh
  .github/workflows/debrepo/repo_remove.sh
  .github/workflows/debrepo/repo_update.sh
  deploy/prepare_deployment.py
Labels: T: Enhancement, C: Build System, PR: Review required, The SCI Campaign

#5280 RPM workflow
  .github/workflows/rpm-package.yml
  .github/workflows/rpmrepo/Dockerfile.fedora
  .github/workflows/rpmrepo/Dockerfile.suse
  .github/workflows/rpmrepo/package_depends.sh
  .github/workflows/rpmrepo/package_filelist.sh
  .github/workflows/rpmrepo/package_prepare.sh
  .github/workflows/rpmrepo/repo_remove.sh
  .github/workflows/rpmrepo/repo_update.sh
Labels: T: Enhancement, C: Build System, PR: Reviewed, The SCI Campaign

#5286 web, job submission: show progress bar on batch page
  html/inc/submit_util.inc
  html/user/submit.php
Labels: P: Minor, T: Enhancement, C: Server - Remote Submission, PR: Reviewed

#5285 Mac: Simplify builds
  mac_build/HowToBuildBOINC_XCode.pdf
  mac_build/HowToBuildBOINC_XCode.rtf
  mac_build/boinc.xcodeproj/project.pbxproj
  mac_build/setupForBOINC.sh
  mac_installer/ReadMe.rtf
Labels: P: Minor, T: Enhancement, C: Build System, PR: Reviewed

#5288 [CI][linux] Create separate flow to build proper linux binaries for packaging
  .github/workflows/linux-package.yml
  deploy/prepare_deployment.py
Labels: P: Major, T: Enhancement, C: Build System

#5293 Mac: Add standard command-comma shortcut for Preferences menu item
  clientgui/AdvancedFrame.cpp
  clientgui/sg_BoincSimpleFrame.cpp
Labels: C: Manager, P: Trivial, T: Bugfix, PR: Reviewed

#5292 Update required wxWidgets to 3.1.3 (first with wxSystemAppearance)
  configure.ac
Labels: P: Minor, C: Build System, T: Bugfix, PR: Reviewed

#5294 Make delimiters argument const so it can (legally) be a string literal.
  clientgui/BOINCListCtrl.cpp
  clientgui/BOINCListCtrl.h
Labels: C: Manager, P: Trivial, T: Bugfix, PR: Reviewed
