Repository BOINC/boinc, pull requests merged in 2023-07, with the labels that each got.

#5299 client: set Content-type of POST requests to text/xml.
  client/http_curl.cpp
Labels: C: Client - Daemon, P: Trivial, T: Bugfix, PR: Reviewed

#5291 [CI][linux] Build DEB package flow
  .github/workflows/deb-package.yml
  .github/workflows/debrepo/Dockerfile
  .github/workflows/debrepo/aptly.bullseye.conf
  .github/workflows/debrepo/aptly.buster.conf
  .github/workflows/debrepo/aptly.focal.conf
  .github/workflows/debrepo/aptly.jammy.conf
  .github/workflows/debrepo/package_depends.sh
  .github/workflows/debrepo/package_prepare.sh
  .github/workflows/debrepo/repo_remove.sh
  .github/workflows/debrepo/repo_update.sh
  .github/workflows/linux-package.yml
  .github/workflows/rpm-package.yml
  .github/workflows/rpmrepo/Dockerfile.fedora
  .github/workflows/rpmrepo/Dockerfile.suse
  .github/workflows/rpmrepo/package_depends.sh
  .github/workflows/rpmrepo/package_filelist.sh
  .github/workflows/rpmrepo/package_prepare.sh
  .github/workflows/rpmrepo/repo_remove.sh
  .github/workflows/rpmrepo/repo_update.sh
Labels: P: Major, T: Enhancement, C: Build System

#5302 Correction for issue #5297
  clientgui/Localization.cpp
  clientgui/Localization.h
Labels: C: Manager - Localization, P: Trivial, T: Enhancement, PR: Reviewed

#5308 web: add "Share on Facebook" and "Share on Twitter" buttons to certificates
  html/inc/cert.inc
  html/user/cert1.php
  html/user/cert_all.php
  html/user/cert_team.php
Labels: C: Web - Project, P: Trivial, T: Enhancement

#5309 crypt_prog: add -verify_string command (to verify a string signature)
  lib/crypt_prog.cpp
Labels: C: Server - Other, P: Trivial, T: Enhancement

#5311 client, Android: if suspend because of battery heat or charge, don't resume for at least 5 minutes.
  client/client_state.h
  client/cs_prefs.cpp
Labels: P: Minor, T: Enhancement, C: Client - Android, PR: Reviewed

#5312 [mingw] Fix build of the cmake project
  lib/CMakeLists.txt
Labels: P: Trivial, C: Build System, T: Bugfix

#5313 [Manager] Add button in event log to display only alerts (errors)
  clientgui/DlgEventLog.cpp
  clientgui/DlgEventLog.h
  clientgui/Events.h
Labels: C: Manager, P: Minor, T: Enhancement, PR: Reviewed

#5314 Locale: Update localization template files
  locale/templates/BOINC-Client.pot
  locale/templates/BOINC-Manager.pot
  locale/templates/BOINC-Project-Generic.pot
  locale/templates/BOINC-Setup.pot
Labels: C: Client - Documentation, C: Manager - Localization, C: Web - Localization, P: Trivial, T: Enhancement

#5316 [CI] Fix paths for renamed vcpkg triplet files
  3rdParty/vcpkg_ports/triplets/default/arm-neon-android.cmake
  3rdParty/vcpkg_ports/triplets/default/arm64-android.cmake
  3rdParty/vcpkg_ports/triplets/default/x64-android.cmake
Labels: P: Major, C: Build System, T: Bugfix
