Repository BOINC/boinc, pull requests merged in 2023-11, with the labels that each got.

#5415 web: if bad data in GPU description field, don't show it.
  html/inc/host.inc
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed

#5418 Build linux packages nightly
  .github/workflows/debrepo/repo_update.sh
  .github/workflows/linux-package.yml
  .github/workflows/rpmrepo/repo_update.sh
Labels: P: Trivial, T: Enhancement, C: Build System

#5419 [CI] Run all actions nightly instead of weekly except coverity
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/source-code-check.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5421 web: fix bug in team search
  html/user/team_search.php
Labels: C: Web - Project, P: Major, T: Bugfix, PR: Reviewed

#5432 Updates and bug fixes for project creation
  apps/Makefile.am
  apps/uppercase.cpp
  apps/uppercase_in
  apps/uppercase_out
  apps/version.xml
  html/inc/db_ops.inc
  html/inc/result.inc
  html/inc/util_ops.inc
  lib/boinc_stdio.h
  py/Boinc/boincxml.py
  tools/backend_lib.h
  tools/demo_query
  tools/demo_submit
  tools/make_project
Labels: C: Server - Setup, P: Minor, T: Bugfix, PR: Reviewed, C: Apps - Samples
