Repository BOINC/boinc, pull requests merged in 2023-05, with the labels that each got.

#5218 Manager (Unix): fix "Show VM" bug
  clientgui/MainDocument.cpp
Labels: C: Manager, P: Major, T: Bugfix, PR: Reviewed

#5221 Manager: fix bug where "estimated completion" and "completion before deadline" task fields switch back and forth to --- during CPU throttling.
  clientgui/ViewWork.cpp
Labels: C: Manager, P: Minor, T: Bugfix, PR: Reviewed

#5209 Add CFBundleShortVersionString to macOS app plist files
  clientgui/mac/SetVersion.cpp
  clientgui/mac/templates/BoincCmd-Info.plist
  clientgui/mac/templates/Info.plist
  clientgui/mac/templates/Installer-Info.plist
  clientgui/mac/templates/PostInstall-Info.plist
  clientgui/mac/templates/ScreenSaver-Info.plist
  clientgui/mac/templates/SystemMenu-Info.plist
  clientgui/mac/templates/Uninstaller-Info.plist
  clientgui/mac/templates/WaitPermissions-Info.plist
Labels: P: Minor, C: Installer - Macintosh, T: Bugfix, PR: Reviewed, The SCI Campaign

#5227 Mac: upgrade to wxWidgets 3.2.2.1
  clientgui/BOINCTaskBar.h
  mac_build/boinc.xcodeproj/project.pbxproj
  mac_build/buildWxMac.sh
  mac_build/dependencyNames.sh
Labels: P: Minor, T: Enhancement, C: Build System, PR: Reviewed

#5228 Update translations
  html/languages/translations/zh_TW.po
  locale/zh_TW/BOINC-Drupal.po
  locale/zh_TW/BOINC-Manager.mo
  locale/zh_TW/BOINC-Manager.po
Labels: C: Manager - Localization, C: Web - Localization, P: Trivial, T: Enhancement, C: Android - Localization

#5229 Apparently ftok() is missing in the wasm C library. Fix this the right way.
  configure.ac
  lib/Makefile.am
  lib/shmem.cpp
  lib/wasm.cpp
Labels: P: Trivial, T: Enhancement, C: Library, PR: Reviewed

#5230 Add missing header file to the lib/CMakeLists.txt file
  lib/CMakeLists.txt
Labels: P: Trivial, C: Library, T: Bugfix

#5232 [libboinc] fix build when integrator tries to link app with libboinc
  lib/filesys.cpp
  lib/str_util.h
  lib/util.cpp
  lib/win_util.cpp
Labels: P: Major, C: Library, T: Bugfix

#5233 client: improve implementation of CPU throttling
  client/app.cpp
  client/cpu_sched.cpp
Labels: C: Client - Daemon, P: Minor, T: Bugfix, PR: Review required

#5238 Mac: add script to notarize BOINC executables
  mac_installer/AddRemoveUser_ReadMe.rtf
  mac_installer/ReadMe.rtf
  mac_installer/notarize_boinc.sh
  mac_installer/release_boinc.sh
Labels: P: Major, T: Enhancement, C: Installer - Macintosh, PR: Reviewed

#5239 Automake: use $(libexecdir) instead of $(libdir)
  apps/Makefile.am
  lib/Makefile.am
  sched/Makefile.am
  tools/Makefile.am
  vda/Makefile.am
Labels: P: Minor, C: Build System, T: Bugfix, PR: Reviewed

#5240 Add cron job to create PR automatically every 1st of January with the updated copyright year
  .github/workflows/update_copyright_year.yml
  ci_tools/update_copyright_year.py
Labels: P: Trivial, T: Enhancement, C: Build System

#5241 Run flows with auto PRs from the mainstream repo only
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/update_copyright_year.yml
Labels: P: Major, T: Enhancement, C: Build System

#5244 Fix screensaver crash bug introduced in PR #5197 commit 689a6eae25
  clientscr/screensaver.cpp
Labels: C: Client - Screen Saver, P: Critical, T: Bugfix, PR: Reviewed

#5245 Mac: update backtrace for MacOS 13.4
  lib/diagnostics.cpp
  lib/mac/mac_backtrace.cpp
  mac_build/boinc.xcodeproj/project.pbxproj
Labels: C: Client - Screen Saver, P: Major, C: Client - Macintosh, T: Bugfix, PR: Reviewed

#5250 [Android] Update gradle and several dependencies
  android/BOINC/.idea/misc.xml
  android/BOINC/app/build.gradle
  android/BOINC/build.gradle
  android/BOINC/gradle/wrapper/gradle-wrapper.jar
  android/BOINC/gradle/wrapper/gradle-wrapper.properties
  android/BOINC/gradlew
  android/BOINC/gradlew.bat
  android/BOINC/settings.gradle
  android/BOINC/versions.properties
  ci_tools/source_code_check.py
Labels: P: Trivial, T: Enhancement, C: Android - Build

#5252 File sandbox fixes
  html/inc/bootstrap.inc
  html/inc/sandbox.inc
  html/user/sandbox.php
Labels: P: Minor, T: Enhancement, C: Server - Remote Submission, PR: Reviewed

#5251 client: the default value for the "suspend_if_no_recent_input" pref should to 0, not 60
  lib/prefs.cpp
Labels: C: Client - Daemon, P: Major, T: Bugfix, PR: Reviewed

#5253 Change wiki links from Trac to Github
  client/sim.cpp
  client/work_fetch.h
  clientgui/SkinManager.cpp
  clientscr/screensaver.cpp
  html/inc/submit.inc
  html/inc/text_transform.inc
  html/inc/util_ops.inc
  html/ops/badge_admin.php
  html/ops/badge_assign_custom.php
  html/ops/check_account_ownership_keys.php
  html/ops/generate_account_ownership_keys.php
  html/ops/index.php
  html/ops/manage_apps.php
  html/ops/single_job_setup.php
  html/ops/size_census.php
  html/project.sample/project.inc
  html/user/download_software.php
  html/user/get_output.php
  html/user/language_select.php
  html/user/submit_rpc_handler.php
  lib/remote_submit.cpp
  lib/remote_submit.h
  sched/assimilator.cpp
  sched/census.cpp
  sched/db_dump.cpp
  sched/file_upload_handler.cpp
  sched/plan_class_spec.cpp
  sched/plan_class_spec.h
  sched/sched_customize.cpp
  sched/sched_limit.cpp
  sched/sched_locality.cpp
  sched/validate_util2.cpp
  sched/validator.cpp
  tools/create_work.cpp
Labels: C: Client - Documentation, C: Server - Documentation, P: Trivial, T: Enhancement, PR: Reviewed

#5202 [Manager] Improve consistency of control labels and accelerators
  clientgui/AdvancedFrame.cpp
  clientgui/DlgAdvPreferencesBase.cpp
  clientgui/DlgDiagnosticLogFlags.cpp
  clientgui/DlgExclusiveApps.cpp
  clientgui/DlgExitMessage.cpp
  clientgui/DlgGenericMessage.cpp
  clientgui/DlgHiddenColumns.cpp
  clientgui/DlgOptions.cpp
  clientgui/DlgSelectComputer.cpp
  clientgui/ViewTransfers.cpp
  clientgui/WizardAttach.cpp
  clientgui/sg_BoincSimpleFrame.cpp
  clientgui/sg_DlgMessages.cpp
  clientgui/sg_DlgPreferences.cpp
  clientgui/wizardex.cpp
Labels: C: Manager, P: Trivial, T: Enhancement, C: Manager - Simple View, PR: Fix required

#5176 [Manager] Show native names for language options, and only those for which translations are available
  clientgui/BOINCGUIApp.cpp
  clientgui/BOINCGUIApp.h
  clientgui/DlgOptions.cpp
  html/inc/language_names.inc
Labels: C: Manager, P: Minor, T: Enhancement, C: Manager - Simple View, PR: Reviewed
