Repository BOINC/boinc, pull requests merged in 2023-02, with the labels that each got.

#5088 [CI][Android] Fix build on ubuntu-latest
  .github/workflows/android.yml
Labels: P: Minor, C: Android - Build, T: Bugfix

#5073 client: enable CPU throttling
  client/app.cpp
  client/client_state.cpp
  client/rr_sim.cpp
Labels: C: Client - Daemon, P: Major, T: Bugfix, PR: Review required

#5076 Manager: don't clear in-use prefs when disable in-use computing
  client/cs_scheduler.cpp
  clientgui/DlgAdvPreferences.cpp
  clientgui/DlgAdvPreferences.h
Labels: C: Manager, P: Major, T: Bugfix, PR: Reviewed

#5085 Account for systems where library directory is named `lib64`
  apps/Makefile.am
  lib/CMakeLists.txt
  lib/Makefile.am
  sched/Makefile.am
  tools/Makefile.am
  vda/Makefile.am
Labels: C: Client - Build, P: Minor, C: Build System, T: Bugfix, PR: Reviewed

#5098 [Linux][Manager][vcpkg] Fix Linux vcpkg manager compilation
  linux/ci_configure_manager.sh
Labels: P: Minor, C: Build System, T: Bugfix, PR: Review required

#5099 [Linux][Manager][vcpkg] Compile Linux vcpkg manager in manifest mode.
  3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
  linux/update_vcpkg_manager.sh
  set-client-version.py
Labels: P: Minor, T: Enhancement, C: Build System, PR: Reviewed

#5100 [vcpkg] Remove versions from manifests files
  3rdParty/vcpkg_ports/configs/apps/android/vcpkg.json
  3rdParty/vcpkg_ports/configs/apps/linux/vcpkg.json
  3rdParty/vcpkg_ports/configs/apps/mingw/vcpkg.json
  3rdParty/vcpkg_ports/configs/client/vcpkg.json
  3rdParty/vcpkg_ports/configs/client/wasm/vcpkg.json
  3rdParty/vcpkg_ports/configs/libs/vcpkg.json
  3rdParty/vcpkg_ports/configs/libs/windows/vcpkg.json
  3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
  3rdParty/vcpkg_ports/configs/msbuild/ARM64/vcpkg.json
  3rdParty/vcpkg_ports/configs/msbuild/x64/vcpkg.json
  set-client-version.py
Labels: P: Trivial, T: Enhancement, C: Build System, PR: Reviewed

#5107 [Linux] Add snap build
  .github/workflows/snap.yml
  .gitignore
  3rdParty/vcpkg_ports/triplets/ci/snap-linux-amd64.cmake
  clientgui/SkinManager.cpp
  deploy/prepare_deployment.py
  linux/update_vcpkg_manager.sh
  set-client-version.py
  snap/gui/boinc.desktop
  snap/gui/boinc.png
  snap/snapcraft.yaml
Labels: P: Minor, T: Enhancement, C: Build System, PR: Reviewed

#5111 client: show file size in event log message when file transfer finishes
  client/pers_file_xfer.cpp
Labels: C: Client - Logging, P: Trivial, T: Enhancement, PR: Reviewed

#5113 [ci] Fix deploy logs
  deploy/prepare_deployment.py
Labels: P: Trivial, C: Build System, T: Bugfix, PR: Reviewed

#5114 [Readme] Add snap and test report status
  README.md
Labels: P: Trivial, C: Build System, T: Informational, PR: Fix required

#5115 Mac: make uninstaller work even if user deleted BOINC Data directory
  mac_installer/PostInstall.cpp
  mac_installer/finish_install.cpp
  mac_installer/uninstall.cpp
Labels: P: Minor, C: Installer - Macintosh, T: Bugfix

#5117 [Readme] Delete test report badge
  README.md
Labels: P: Trivial, C: Build System, T: Bugfix, PR: Reviewed
