Repository BOINC/boinc, pull requests merged in 2024-09, with the labels that each got.

#5788 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/update_actions.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5790 [linux][manager] Fix fonts on Advanced Computing Preferences dialog.
  clientgui/DlgAdvPreferencesBase.cpp
Labels: C: Manager, P: Trivial, T: Bugfix

#5754 [sched] add wsl plan class
  sched/plan_class_spec.cpp
  sched/plan_class_spec.h
  sched/plan_class_spec.xml.sample
  sched/sched_customize.cpp
Labels: C: Server - Scheduler, P: Minor, T: Enhancement, PR: Review required

#5792 scheduler: fix WSL plan class
  html/inc/boinc_db.inc
  html/ops/db_update.php
  sched/plan_class_spec.cpp
Labels: C: Server - Scheduler, T: Bugfix

#5791 Add wsl_wrapper
  .github/workflows/linux.yml
  client/app_start.cpp
  client/app_test.cpp
  client/client_state.cpp
  client/client_state.h
  client/cs_cmdline.cpp
  client/cs_files.cpp
  client/cs_statefile.cpp
  client/file_names.cpp
  client/hostinfo_wsl.cpp
  client/project.h
  lib/win_util.cpp
  lib/win_util.h
  lib/wslinfo.cpp
  lib/wslinfo.h
  linux/arm64/build_curl_arm64.sh
  linux/arm64/build_example_arm64.sh
  linux/arm64/build_libraries_arm64.sh
  linux/arm64/build_openssl_arm64.sh
  samples/worker/worker.cpp
  samples/wsl_wrapper/wsl_wrapper.cpp
Labels: C: Client - Daemon, T: Enhancement, C: Library, PR: Reviewed, C: Apps - WslWrapper

#5795 fix possible buffer overflow
  client/sandbox.cpp
Labels: C: Client - Daemon, T: Bugfix, PR: Reviewed

#5796 client: fix potential byte count overflow
  client/gui_rpc_server_ops.cpp
Labels: C: Client - Daemon, T: Bugfix, PR: Reviewed

#5797 client: get 'in use' state only if computing preferences need it.
  client/client_state.cpp
  client/cs_prefs.cpp
  lib/prefs.h
Labels: C: Client - Daemon, P: Minor, T: Enhancement

#5798 [coverity] run builds nightly instead of weekly
  .github/workflows/coverity.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5801 client: add missing clause in idle check logic
  lib/prefs.h
Labels: C: Client - Daemon, P: Major, T: Bugfix, PR: Reviewed

#5803 validator: handle transient errors
  sched/db_purge.cpp
  sched/script_validator.cpp
  sched/validate_util2.cpp
  sched/validate_util2.h
Labels: C: Server - Validator, P: Minor, T: Bugfix

#5804 [Windows] Fix several build warnings
  api/graphics2_win.cpp
  api/gutil.cpp
  client/boinc_cmd.cpp
  clientgui/common/wxPieCtrl.cpp
  clientscr/ss_app.cpp
  lib/common_defs.h
  lib/crypt_prog.cpp
  samples/example_app/slide_show.cpp
  samples/example_app/uc2.cpp
  samples/example_app/uc2_graphics.cpp
  samples/nvcuda/cuda.cpp
  samples/openclapp/openclapp.cpp
  samples/sporadic/sporadic.cpp
  samples/worker/worker.cpp
  samples/wrappture/wrappture.cpp
  samples/wrappture/wrappture_example.cpp
  tests/unit-tests/lib/test_parse.cpp
  tests/unit-tests/lib/test_str_util.cpp
Labels: P: Trivial, T: Enhancement, C: Build System

#5805 remote job submission: remove debugging code
  html/user/get_output.php
Labels: C: Server - Remote Submission, T: Bugfix, PR: Reviewed

#5806 [windows] simplify *.vcxproj files by removing duplicates and moving the most of the common properties to the imported boinc.props and pch.props files
  set-vboxwrapper-version.py
  set-worker-version.py
  set-wrapper-version.py
  win_build/boinc.props
  win_build/boinc_cli.vcxproj
  win_build/boinc_os_ss.vcxproj
  win_build/boinc_ss.vcxproj
  win_build/boinccas.vcxproj
  win_build/boinccmd.vcxproj
  win_build/boinclog.vcxproj
  win_build/boincmgr.vcxproj
  win_build/boincsvcctrl.vcxproj
  win_build/boinctray.vcxproj
  win_build/crypt_prog.vcxproj
  win_build/example_app_atiopencl.vcxproj
  win_build/example_app_multi_thread.vcxproj
  win_build/example_app_nvcuda.vcxproj
  win_build/example_app_nvopencl.vcxproj
  win_build/glut.vcxproj
  win_build/htmlgfx.vcxproj
  win_build/image_libs.vcxproj
  win_build/jpeglib.vcxproj
  win_build/libboinc.vcxproj
  win_build/libboincapi.vcxproj
  win_build/libboincopencl.vcxproj
  win_build/libboinczip.vcxproj
  win_build/libgraphics2.vcxproj
  win_build/pch.props
  win_build/sim.vcxproj
  win_build/sleeper.vcxproj
  win_build/slide_show.vcxproj
  win_build/sporadic.vcxproj
  win_build/test_boinc_zip.vcxproj
  win_build/test_boinc_zip_zlib_conflicts.vcxproj
  win_build/uc2.vcxproj
  win_build/uc2_dll.vcxproj
  win_build/uc2_graphics.vcxproj
  win_build/unittests.vcxproj
  win_build/vboxwrapper.vcxproj
  win_build/vcpkg_3rdparty_dependencies.vcxproj
  win_build/worker.vcxproj
  win_build/wrapper.vcxproj
  win_build/wrappture_example.vcxproj
  win_build/wsl_wrapper.vcxproj
Labels: T: Enhancement, C: Build System

#5808 fix typo in script to cancel WUs
  html/inc/util_ops.inc
  html/ops/cancel_workunits.php
Labels: C: Server - Setup, P: Minor, T: Bugfix, PR: Reviewed

#5809 [ci] update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/android.yml
  .github/workflows/update_copyright_year.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5814 [ci] update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/update_copyright_year.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5817 [ci] fix windows cmake build
  .github/workflows/windows.yml
  deploy/prepare_deployment.py
Labels: P: Trivial, C: Build System, T: Bugfix

#5819 [ci] update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/android.yml
  .github/workflows/check_custom_vcpkg_ports.yml
  .github/workflows/coverity.yml
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/source-code-check.yml
  .github/workflows/test-report.yml
  .github/workflows/update_actions.yml
  .github/workflows/update_copyright_year.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: T: Enhancement, C: Build System

#5820 Update is_extpack_installed
  samples/vboxwrapper/vbox_vboxmanage.cpp
Labels: P: Major, T: Enhancement, C: Apps - VboxWrapper, PR: Reviewed

#5823 Set virtualbox vrde-property
  samples/vboxwrapper/vbox_vboxmanage.cpp
Labels: P: Major, C: Apps - VboxWrapper, T: Bugfix, PR: Reviewed
