Repository BOINC/boinc, pull requests merged in 2024-04, with the labels that each got.

#5574 web: add support for showing long text with a 'more' button
  html/inc/more.inc
  html/inc/pm.inc
  html/inc/team.inc
  html/inc/util.inc
  html/user/account_finish.php
  html/user/forum_post.php
  html/user/user_search.php
Labels: C: Web - Project, P: Critical, P: Minor, T: Enhancement, PR: Reviewed

#5575 [liblzma] Remove custom liblzma port.
  3rdParty/vcpkg_ports/ports/liblzma/add_support_ios.patch
  3rdParty/vcpkg_ports/ports/liblzma/build-tools.patch
  3rdParty/vcpkg_ports/ports/liblzma/fix_config_include.patch
  3rdParty/vcpkg_ports/ports/liblzma/portfile.cmake
  3rdParty/vcpkg_ports/ports/liblzma/usage
  3rdParty/vcpkg_ports/ports/liblzma/vcpkg-cmake-wrapper.cmake
  3rdParty/vcpkg_ports/ports/liblzma/vcpkg.json
  3rdParty/vcpkg_ports/ports/liblzma/win_output_name.patch
Labels: P: Trivial, T: Enhancement, C: Build System

#5569 [drupal] added Apple GPU support to project preferences
  drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
Labels: C: Web - Project, T: Enhancement

#5576 Fix sporadic codecov uploads fails
  .codecov.yml
  .github/workflows/test-report.yml
Labels: P: Minor, C: Build System, T: Bugfix

#5579 [CI] Put correct tokens
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/test-report.yml
  .github/workflows/windows.yml
Labels: P: Minor, C: Build System, T: Bugfix

#5580 [CI] Download only artifacts with test reports for the test report workflow
  .github/workflows/test-report.yml
Labels: P: Minor, C: Build System, T: Bugfix

#5578 web / job submission: move admin links to main page (submit.php)
  html/user/manage_app.php
  html/user/submit.php
Labels: C: Web - Project, P: Minor, T: Enhancement, PR: Reviewed

#5584 [CI] Update github actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/update_actions.yml
  .github/workflows/update_copyright_year.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5585 Report TIMEOUT from vbm_popen
  samples/vboxwrapper/vbox_common.cpp
Labels: P: Major, C: Apps - VboxWrapper, T: Bugfix, PR: Reviewed

#5577 client: if GPU is missing, discard app versions and results that refer to it.
  client/cs_statefile.cpp
Labels: C: Client - Daemon, P: Minor, T: Enhancement, PR: Reviewed

#5587 Vboxwrapper - handling of outdated vboxmanage command options
  samples/vboxwrapper/vbox_common.cpp
  samples/vboxwrapper/vbox_vboxmanage.cpp
Labels: P: Major, C: Apps - VboxWrapper, T: Bugfix, PR: Reviewed

#5591 [Windows] Fix client crash
  lib/win_util.cpp
Labels: P: Critical, C: Client - Windows, T: Bugfix

#5593 [CI] Update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/android.yml
  .github/workflows/flutter-ubuntu.yml
  .github/workflows/flutter-windows.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/test-report.yml
  .github/workflows/update_actions.yml
  .github/workflows/update_copyright_year.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5596 [CI] fix build
  3rdParty/vcpkg_ports/ports/dbus/cmake.dep.patch
  3rdParty/vcpkg_ports/ports/dbus/getpeereid.patch
  3rdParty/vcpkg_ports/ports/dbus/libsystemd.patch
  3rdParty/vcpkg_ports/ports/dbus/pkgconfig.patch
  3rdParty/vcpkg_ports/ports/dbus/portfile.cmake
  3rdParty/vcpkg_ports/ports/dbus/vcpkg.json
Labels: P: Major, C: Build System, T: Bugfix

#5598 Fix possible endless loop
  samples/vboxwrapper/vbox_vboxmanage.cpp
Labels: P: Major, C: Apps - VboxWrapper, T: Bugfix, PR: Reviewed

#5599 [CI] Remove custom dbus vcpkg port that was fixed and updated on upstream
  3rdParty/vcpkg_ports/ports/dbus/cmake.dep.patch
  3rdParty/vcpkg_ports/ports/dbus/getpeereid.patch
  3rdParty/vcpkg_ports/ports/dbus/libsystemd.patch
  3rdParty/vcpkg_ports/ports/dbus/pkgconfig.patch
  3rdParty/vcpkg_ports/ports/dbus/portfile.cmake
  3rdParty/vcpkg_ports/ports/dbus/vcpkg.json
Labels: P: Trivial, T: Enhancement, C: Build System

#5600 [CI] Add linux packages for Fedora 40
  .github/workflows/linux-package.yml
  .github/workflows/rpmrepo/package_depends.sh
  .github/workflows/rpmrepo/package_filelist.sh
Labels: P: Major, T: Enhancement, C: Build System, C: Installer - Linux

#5603 [CI] Build linux packages for Ubuntu 24.04
  .github/workflows/debrepo/aptly.noble.conf
  .github/workflows/debrepo/package_depends.sh
  .github/workflows/linux-package.yml
Labels: P: Major, T: Enhancement, C: Build System, C: Installer - Linux

#5604 [CI] Replace unofficial PPA with the official snap package of aws cli
  snap/snapcraft.yaml
Labels: P: Trivial, T: Enhancement, C: Build System

#5606 More/Less text feature: add a version that returns string so you can use it in table_row() etc.
  html/inc/more.inc
Labels: C: Web - Project, P: Trivial, T: Enhancement, PR: Reviewed

#5607 [CI] Update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/android.yml
  .github/workflows/coverity.yml
  .github/workflows/flutter-macos.yml
  .github/workflows/flutter-ubuntu.yml
  .github/workflows/flutter-windows.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/source-code-check.yml
  .github/workflows/test-report.yml
  .github/workflows/update_actions.yml
  .github/workflows/update_copyright_year.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: P: Trivial, T: Enhancement, C: Build System
