Repository BOINC/boinc, pull requests merged in 2024-12, with the labels that each got.

#5929 docker_wrapper: allow passing args into container
  client/app_test.cpp
  client/cs_apps.cpp
  html/user/buda_submit.php
  samples/docker_wrapper/docker_wrapper.cpp
  samples/docker_wrapper/test/main.sh
Labels: C: Client, C: Web - Project, PR: Enhancement, C: Apps - DockerWrapper

#5932 BUDA: support per-batch and per-job command-line args
  configure.ac
  html/inc/sandbox.inc
  html/user/buda.php
  html/user/buda_submit.php
  html/user/sandbox.php
  lib/str_util.cpp
  samples/docker_wrapper/docker_wrapper.cpp
  samples/docker_wrapper/test_buda/Dockerfile_worker_1
  samples/docker_wrapper/test_buda/Dockerfile_worker_2
  samples/docker_wrapper/test_buda/main_2.sh
  samples/docker_wrapper/test_buda/main_3.sh
  samples/worker/Makefile
  samples/worker/worker.cpp
  tools/create_work.cpp
  version.h
  win_build/worker.vcxproj
Labels: C: Web - Project, PR: Enhancement, C: Apps - Worker

#5935 [Windows] Set correct platform name when running BOINC client on Windows on ARM.
  client/cs_platforms.cpp
  client/hostinfo_win.cpp
  lib/hostinfo.h
Labels: C: Client, PR: Bugfix, OS: Windows

#5938 fix problem where wrapper unzips input files each time it restarts
  client/app.h
  client/app_control.cpp
  client/app_start.cpp
  client/client_state.cpp
  client/client_state.h
  client/main.cpp
  samples/wrapper/wrapper.cpp
Labels: C: Client, C: Apps - Wrapper, PR: Bugfix

#5937 [windows][installer] clean-up unused strings and resources
  installer/ActionText.cpp
  installer/ActionText.h
  installer/ActionTextTable.cpp
  installer/ActionTextTable.h
  installer/Component.cpp
  installer/Component.h
  installer/Control.cpp
  installer/Control.h
  installer/Dialog.cpp
  installer/Dialog.h
  installer/DialogTable.cpp
  installer/DialogTable.h
  installer/Directory.cpp
  installer/Directory.h
  installer/DirectoryTable.cpp
  installer/DirectoryTable.h
  installer/Error.cpp
  installer/Error.h
  installer/ErrorTable.cpp
  installer/ErrorTable.h
  installer/Feature.cpp
  installer/Feature.h
  installer/FeatureTable.cpp
  installer/FeatureTable.h
  installer/InstallerStrings.cpp
  installer/InstallerStrings.h
  installer/JsonHelper.h
  installer/LaunchCondition.cpp
  installer/LaunchCondition.h
  installer/LaunchConditionTable.cpp
  installer/LaunchConditionTable.h
  installer/Property.cpp
  installer/Property.h
  installer/PropertyTable.cpp
  installer/PropertyTable.h
  installer/RadioButton.cpp
  installer/RadioButton.h
  installer/RadioButtonTable.cpp
  installer/RadioButtonTable.h
  installer/ServiceInstall.cpp
  installer/ServiceInstall.h
  installer/Shortcut.cpp
  installer/Shortcut.h
  installer/SummaryInformationTable.cpp
  installer/SummaryInformationTable.h
  installer/UIText.cpp
  installer/UIText.h
  installer/UITextTable.cpp
  installer/UITextTable.h
  installer/boinc.json
  installer/locale/en.json
Labels: PR: Enhancement, OS: Windows, C: Installer

#5939 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/coverity.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#5945 web: make sandbox file list sortable by name, size, or date
  html/inc/sandbox.inc
  html/inc/util.inc
  html/user/buda.php
  html/user/sandbox.php
  html/user/submit.php
Labels: C: Server, PR: Enhancement

#5944 Convert issue templates from GHFM to YAML.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other-issues.md
  .github/ISSUE_TEMPLATE/other-issues.yml
Labels: C: Undetermined, PR: Enhancement, PR: Fix required

#5947 Refactor boinc.json structure a little bit.
  installer/Control.cpp
  installer/Control.h
  installer/ControlTable.cpp
  installer/Installer.cpp
  installer/InstallerStrings.cpp
  installer/InstallerStrings.h
  installer/RadioButton.cpp
  installer/RadioButton.h
  installer/RadioButtonTable.cpp
  installer/RadioButtonTable.h
  installer/boinc.json
  installer/locale/en.json
  installer/main.cpp
  win_build/installer_setup.vcxproj
Labels: PR: Enhancement, OS: Windows, C: Installer

#5949 [linux] update custom librsvg port
  3rdParty/vcpkg_ports/ports/librsvg/fix-libxml2-2.13.5.patch
  3rdParty/vcpkg_ports/ports/librsvg/portfile.cmake
  3rdParty/vcpkg_ports/ports/librsvg/vcpkg.json
Labels: PR: Enhancement, C: Build System, OS: Linux

#5951 remove useless redirect
  html/user/user_agreetermsofuse.php
Labels: C: Web - Project, PR: Enhancement, PR: Review required

#5957 [windows] Remove more unused strings from the boinc.json file
  installer/boinc.json
  installer/locale/en.json
Labels: PR: Enhancement, OS: Windows, C: Installer

#5958 [windows] adjust set-client-version.py file to update boinc.json file
  set-client-version.py
Labels: PR: Enhancement, OS: Windows, C: Installer

#5959 web: fix ops/sample_table_stats.php (shows details of DB tables)
  html/ops/index.php
  html/ops/sample_table_stats.php
Labels: C: Web - Project, PR: Enhancement

#5960 client, server, web: enable BUDA GPU apps
  client/app.cpp
  client/app_config.cpp
  client/app_control.cpp
  client/app_start.cpp
  client/client_state.cpp
  client/client_types.cpp
  client/client_types.h
  client/coproc_sched.cpp
  client/coproc_sched.h
  client/cpu_sched.cpp
  client/cs_scheduler.cpp
  client/cs_statefile.cpp
  client/log_flags.cpp
  client/project.cpp
  client/result.cpp
  client/result.h
  client/rr_sim.cpp
  client/sim.cpp
  client/sim_util.cpp
  client/work_fetch.cpp
  db/boinc_db_types.h
  html/inc/app_types.inc
  html/inc/prefs_project.inc
  html/inc/submit_util.inc
  html/inc/util.inc
  html/user/buda.php
  html/user/buda_submit.php
  html/user/get_output3.php
  sched/plan_class_spec.xml.sample
  sched/sched_array.cpp
  sched/sched_assign.cpp
  sched/sched_customize.cpp
  sched/sched_locality.cpp
  sched/sched_nci.cpp
  sched/sched_resend.cpp
  sched/sched_score.cpp
  sched/sched_score.h
  sched/sched_send.cpp
  sched/sched_send.h
  sched/sched_shmem.cpp
  sched/sched_types.h
  sched/sched_version.cpp
Labels: C: Client, C: Server, C: Server - Scheduler, PR: Enhancement

#5962 fix vulnerability in yucky consent code
  html/inc/consent.inc
  html/user/user_agreetermsofuse_action.php
Labels: C: Web - Project, PR: Bugfix

#5964 web: remove vulnerabilities in tree_threader and in unused badge function
  html/inc/util_ops.inc
  html/user/tree_threader.php
Labels: C: Web - Project, PR: Bugfix

#5966 fix link on bbcode page
  html/user/bbcode.php
Labels: C: Web, PR: Bugfix

#5967 web: fix various vulnerabilities
  html/inc/consent.inc
  html/inc/prefs_util.inc
  html/inc/user_util.inc
  html/inc/util.inc
  html/inc/util_basic.inc
  html/user/am_set_host_info.php
  html/user/buda.php
  html/user/manage_app.php
  html/user/manage_project.php
  html/user/sandbox.php
  html/user/team_forum.php
  html/user/team_founder_transfer_action.php
Labels: C: Web - Project, PR: Bugfix

#5968 web: fix various XSS vulnerabilities
  html/inc/util_basic.inc
  html/user/get_output.php
  html/user/get_output3.php
  html/user/job_file.php
  html/user/openid_login.php
  html/user/prefs_edit.php
  html/user/submit_rpc_handler.php
Labels: C: Web - Project, PR: Bugfix

#5970 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/update_actions.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#5862 [Manager] Gray out projects in project wizard that are already attached
  clientgui/ProjectInfoPage.cpp
  clientgui/ProjectInfoPage.h
Labels: C: Manager, PR: Enhancement

#5974 [ci] fix upload windows logs on ci
  .github/workflows/windows.yml
Labels: C: Build System, PR: Bugfix

#5973 Client: add some error reporting to WSL detection
  client/hostinfo_wsl.cpp
  lib/util.cpp
  lib/win_util.cpp
  lib/win_util.h
  samples/wsl_wrapper/wsl_wrapper.cpp
Labels: C: Client, PR: Enhancement, C: Library

#5976 [ci][linux] add modern way of adding DEB repositories
  .github/workflows/linux-package.yml
Labels: PR: Enhancement, C: Build System

#5978 [ci] update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/update_copyright_year.yml
Labels: PR: Enhancement, C: Build System

#5981 [ci][windows] sign executables using Azure
  .github/workflows/windows.yml
  ci_tools/check_custom_vcpkg_ports_for_updates.py
  ci_tools/create_signing_metadata.py
  ci_tools/source_code_check.py
  ci_tools/trailing_whitespaces_check.py
  ci_tools/update_actions.py
  win_build/boinc.sln
  win_build/boinc_signing.targets
  win_build/installer.vcxproj
  win_build/installer_msi.vcxproj
  win_build/installer_setup.vcxproj
Labels: PR: Enhancement, C: Build System, OS: Windows, C: Installer

#5982 [manager] fix crash when launching BOINC Manager on the fresh system without any projects connected
  clientgui/ProjectInfoPage.cpp
Labels: C: Manager, PR: Bugfix

#5984 client: fix bug that caused client to treat all jobs as 1-CPU
  client/client_types.cpp
Labels: C: Client
