Repository BOINC/boinc, pull requests merged in 2024-07, with the labels that each got.

#5670 client: add some error checking for --app_test, and improve comments
  client/app_test.cpp
  client/cs_cmdline.cpp
Labels: P: Trivial, T: Enhancement, PR: Reviewed, C: Apps - Samples

#5671 client: fix terminology
  client/client_state.cpp
  client/cs_prefs.cpp
Labels: C: Client - Daemon, P: Trivial, T: Enhancement

#5674 [ci] fix
  .github/workflows/linux.yml
Labels: P: Blocker, C: Build System, T: Bugfix

#5673 [ci] Add boinccas.dll to the uploaded artifacts
  .github/workflows/windows.yml
  deploy/prepare_deployment.py
Labels: P: Trivial, T: Enhancement, C: Build System

#5678 client: don't put HTML in event log messages
  client/client_msgs.cpp
  client/current_version.cpp
Labels: C: Client - Daemon, P: Trivial, T: Enhancement, PR: Reviewed

#5680 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/flutter-ubuntu.yml
  .github/workflows/flutter-windows.yml
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/test-report.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5681 [Drupal] Updated Android download instructions
  drupal/sites/default/boinc/modules/boincuser/boincuser.module
Labels: C: Web - Project, T: Enhancement, PR: Reviewed

#5686 [Manager] Make DlgGenericMessage dialog more generic.
  clientgui/AdvancedFrame.cpp
  clientgui/DlgGenericMessage.cpp
  clientgui/DlgGenericMessage.h
Labels: C: Manager, P: Minor, T: Enhancement

#5687 [Manager] Add possibility to navigate to the download page when the new version of BOINC is available.
  clientgui/MainDocument.cpp
Labels: C: Manager, P: Trivial, T: Enhancement

#5688 [Manager] Add possibility to hide 'Another instance of BOINC Manager is already running' message
  clientgui/BOINCGUIApp.cpp
  clientgui/BOINCGUIApp.h
Labels: C: Manager, P: Minor, T: Enhancement

#5658 vboxwrapper: don't create projects/virtualbox
  samples/vboxwrapper/vbox_vboxmanage.cpp
Labels: P: Major, C: Apps - VboxWrapper, T: Bugfix

#5696 server status page: fix PHP warning
  html/user/server_status.php
Labels: C: Web - Project, P: Minor, T: Bugfix

#5698 make buttons more legible
  html/inc/bootstrap.inc
  html/inc/email.inc
  html/inc/pm.inc
  html/inc/prefs.inc
  html/inc/team.inc
  html/inc/user.inc
  html/inc/util.inc
  html/user/forum_forum.php
  html/user/forum_reply.php
  html/user/forum_search.php
  html/user/host_venue_action.php
  html/user/profile_menu.php
  html/user/sample_index.php
  html/user/show_coproc.php
  html/user/team_admins.php
  html/user/team_change_founder_form.php
  html/user/user_search.php
  html/user/view_profile.php
Labels: C: Web - Project, P: Minor, T: Enhancement

#5699 web: increase size of Subject field in message board create/edit form
  html/user/forum_edit.php
Labels: C: Web - Project, P: Trivial, T: Enhancement, PR: Reviewed

#5702 web tweaks
  html/inc/host.inc
  html/inc/team.inc
  html/inc/user.inc
  html/user/custom_dark.css
  html/user/edit_forum_preferences_form.php
  html/user/show_user.php
Labels: C: Web - Project, P: Minor, T: Enhancement, PR: Reviewed

#5705 web: fix bug that hid GPUs in host page
  html/inc/host.inc
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed

#5704 client: fix minor prefs parsing bug
  lib/prefs.cpp
Labels: C: Client - Daemon, P: Minor, T: Bugfix, PR: Reviewed

#5710 web: in PM send to multiple users, but names/IDs on separate lines
  html/inc/pm.inc
  html/user/pm.php
Labels: C: Web - Private Messages, P: Minor, T: Bugfix, PR: Reviewed

#5711 update_versions: keep going if find bad app version directory
  tools/update_versions
Labels: C: Server - Other, T: Bugfix, PR: Reviewed

#5712 db_dump: report encoding correctly ('utf-8' rather than 'iso-8859-1')
  sched/db_dump.cpp
Labels: C: Server - Other, T: Bugfix, PR: Reviewed

#5713 [ci] update actions
  .github/workflows/snap.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5714 web: fix edge case in bbcode processing
  html/inc/text_transform.inc
Labels: C: Web - Forums, T: Bugfix

#5715 forums: when quote a message, identify its sender and date
  html/user/forum_reply.php
Labels: C: Web - Forums, P: Trivial, T: Enhancement, PR: Reviewed

#5717 web: don't allow blocking PMs from a moderator or admin.
  html/inc/forum.inc
  html/inc/pm.inc
  html/user/pm.php
Labels: C: Web - Private Messages, T: Enhancement, PR: Reviewed

#5718 [vcpkg][linux] Add custom gdk-pixbuf and librsvg vcpkg ports
  3rdParty/vcpkg_ports/configs/manager/linux/vcpkg.json
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/add_optional_svg_support.patch
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/fix-static-deps.patch
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/fix_build_error_windows.patch
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/loaders-cache.patch
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/portfile.cmake
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/use-libtiff-4-pkgconfig.patch
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/vcpkg.json
  3rdParty/vcpkg_ports/ports/librsvg/CMakeLists.txt
  3rdParty/vcpkg_ports/ports/librsvg/config.h.linux
  3rdParty/vcpkg_ports/ports/librsvg/fix_io_svg_for_static_build.patch
  3rdParty/vcpkg_ports/ports/librsvg/portfile.cmake
  3rdParty/vcpkg_ports/ports/librsvg/unofficial-librsvg-config.cmake
  3rdParty/vcpkg_ports/ports/librsvg/usage
  3rdParty/vcpkg_ports/ports/librsvg/vcpkg.json
  clientgui/BOINCGUIApp.cpp
  linux/ci_configure_manager.sh
Labels: C: Manager, P: Minor, C: Build System, T: Bugfix, C: Installer - Linux

#5719 [linux] remove unused '--enable-vcpkg' configure parameter
  android/build_boinc_armv6.sh
  android/build_example_arm64.sh
  android/build_example_armv6.sh
  android/build_example_x86_64.sh
  configure.ac
  samples/Makefile.am
  samples/condor/Makefile
  samples/example_app/Makefile
  samples/sporadic/Makefile
  wasm/ci_configure_client.sh
Labels: P: Trivial, T: Enhancement, C: Build System

#5720 [ci] check for upstream updates of the custom vcpkgs ports
  .github/workflows/check_custom_vcpkg_ports.yml
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/vcpkg.json
  ci_tools/check_custom_vcpkg_ports_for_updates.py
Labels: P: Trivial, T: Enhancement, C: Build System

#5721 Add the ability to subscribe to forums (as well as threads).
  db/schema.sql
  html/inc/forum.inc
  html/inc/forum_db.inc
  html/inc/forum_email.inc
  html/inc/notify.inc
  html/inc/user.inc
  html/inc/util.inc
  html/ops/notify.php
  html/user/forum_forum.php
  html/user/forum_thread.php
Labels: C: Web - Forums, T: Enhancement, PR: Reviewed
