Repository BOINC/boinc, pull requests merged in 2024-02, with the labels that each got.

#5507 [CI] Fix build
  3rdParty/vcpkg_ports/triplets/ci/arm64-osx.cmake
Labels: P: Major, C: Build System, T: Bugfix

#5510 Remove permanently closed stats website
  html/inc/stats_sites.inc
Labels: C: Web - Project, P: Trivial, T: Enhancement

#5513 rename templates to match cookbook
  samples/worker/worker_in
  samples/worker/worker_out
  tools/create_work.cpp
Labels: C: Server - Setup, P: Trivial, T: Bugfix, PR: Reviewed

#5505 client/server/web: add 'Apple GPU' as an official GPU type.
  client/client_state.cpp
  client/gpu_detect.cpp
  client/gpu_detect.h
  client/gpu_intel.cpp
  client/gpu_opencl.cpp
  client/log_flags.cpp
  client/work_fetch.cpp
  db/boinc_db_types.h
  html/inc/common_defs.inc
  html/inc/prefs_project.inc
  html/inc/result.inc
  html/inc/util.inc
  html/inc/util_basic.inc
  html/inc/util_ops.inc
  html/user/gpu_list.php
  html/user/gpu_ratios.php
  lib/coproc.cpp
  lib/coproc.h
  lib/gui_rpc_client.h
  lib/gui_rpc_client_ops.cpp
  lib/gui_rpc_client_print.cpp
  lib/mac/mac_spawn.cpp
  sched/plan_class_spec.cpp
  sched/plan_class_spec.h
  sched/sched_customize.cpp
  sched/sched_customize.h
  sched/sched_send.cpp
  sched/sched_types.cpp
  sched/sched_types.h
  sched/sched_util_basic.cpp
  version.h
  version.h.in
Labels: C: Server - Scheduler, P: Major, T: Enhancement, C: Client - Macintosh, PR: Review required

#5515 server: add error-checking to demo_submit script
  tools/demo_submit
Labels: C: Server - Other, P: Minor, T: Enhancement, PR: Reviewed

#5517 client: make the --app_test feature more general.
  client/app_test.cpp
  client/client_types.cpp
  client/client_types.h
Labels: P: Minor, T: Enhancement, PR: Reviewed, C: Apps - Samples

#5519 Build linux packages for Debian 12 and Fedora 39
  .github/workflows/debrepo/aptly.bookworm.conf
  .github/workflows/debrepo/package_depends.sh
  .github/workflows/linux-package.yml
  .github/workflows/rpmrepo/package_filelist.sh
Labels: P: Minor, T: Enhancement, C: Build System, C: Installer - Linux
