Repository BOINC/boinc, pull requests merged in 2024-10, with the labels that each got.

#5828 Added a placeholder install step
  samples/condor/Makefile
  samples/multi_thread/Makefile
Labels: C: Build System, T: Bugfix, hacktoberfest-accepted

#5829 samples: unify installation target
  .gitignore
  samples/condor/Makefile
  samples/example_app/Makefile
  samples/multi_thread/Makefile
  samples/openclapp/Makefile
  samples/sporadic/Makefile
  samples/vboxmonitor/Makefile
  samples/vboxwrapper/Makefile
  samples/wrappture/Makefile
Labels: P: Trivial, T: Enhancement, C: Build System

#5830 client and API: add plan class to APP_INIT_DATA
  client/app_start.cpp
  client/client_types.cpp
  lib/app_ipc.cpp
  lib/app_ipc.h
  lib/proxy_info.h
Labels: C: Client - Daemon, P: Minor, T: Enhancement, C: Library, PR: Reviewed

#5831 web: fix PHP warning from showing subscriptions without user login
  html/inc/forum.inc
  html/user/forum_forum.php
Labels: C: Web - Forums, P: Minor, T: Bugfix, PR: Reviewed

#5832 web: forums: fix 'mark all threads as read' function
  html/user/forum_index.php
Labels: C: Web - Forums, P: Minor, T: Bugfix, PR: Reviewed

#5837 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/coverity.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: P: Trivial, T: Enhancement, C: Build System

#5838 show error if project dir rename fails
  client/cs_scheduler.cpp
Labels: C: Client - Daemon, P: Trivial, T: Enhancement, PR: Reviewed

#5840 lib/Makefile.mingw: add boinc_stdio.h to install headers
  lib/Makefile.mingw
Labels: P: Trivial, C: Library, T: Bugfix, PR: Reviewed

#5848 [ci] update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/android.yml
  .github/workflows/check_custom_vcpkg_ports.yml
  .github/workflows/coverity.yml
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/source-code-check.yml
  .github/workflows/test-report.yml
  .github/workflows/update_actions.yml
  .github/workflows/update_copyright_year.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: T: Enhancement, C: Build System

#5851 [Manager] Add application name to task properties window
  clientgui/DlgItemProperties.cpp
Labels: C: Manager, P: Trivial, T: Enhancement, PR: Reviewed, hacktoberfest-accepted

#5852 web: fix PHP8 deprecation warnings
  html/inc/forum_db.inc
  html/inc/pm.inc
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Reviewed

#5846 web: don't allow special chars in user names.
  html/inc/user_util.inc
  html/user/edit_user_info_action.php
Labels: C: Server - Setup, P: Critical, T: Bugfix, PR: Review required

#5850 Remove unused functions
  client/app.h
  client/client_state.h
  client/cs_notice.h
  client/http_curl.h
  client/project.h
  clientgui/AsyncRPC.h
  clientgui/BOINCListCtrl.h
  clientgui/DlgEventLog.h
  clientgui/DlgOptions.h
  clientgui/MainDocument.h
  clientgui/ViewNotices.h
  clientgui/sg_BoincSimpleFrame.h
  clientgui/sg_DlgPreferences.h
  lib/app_ipc.h
  lib/common_defs.h
  lib/gui_rpc_client.h
  lib/prefs.h
  lib/str_util.h
  lib/url.h
Labels: C: Client - Daemon, C: Manager, P: Trivial, T: Enhancement, C: Library, PR: Review required, hacktoberfest-accepted

#5853 subs should be empty by default, not null
  html/user/forum_forum.php
Labels: C: Web - Project, P: Minor, T: Bugfix, PR: Review required

#5855 Add docker_wrapper and associated client/server changes
  client/Makefile.linux
  client/app_test.cpp
  client/client_state.cpp
  client/cs_scheduler.cpp
  client/hostinfo_unix.cpp
  client/hostinfo_wsl.cpp
  lib/common_defs.h
  lib/hostinfo.cpp
  lib/hostinfo.h
  lib/util.cpp
  lib/util.h
  lib/win_util.cpp
  lib/win_util.h
  lib/wslinfo.cpp
  lib/wslinfo.h
  samples/docker_wrapper/Makefile
  samples/docker_wrapper/docker_wrapper.cpp
  samples/docker_wrapper/test_copy/Dockerfile_copy
  samples/docker_wrapper/test_copy/in
  samples/docker_wrapper/test_copy/job_copy.toml
  samples/docker_wrapper/test_mount/Dockerfile_mount
  samples/docker_wrapper/test_mount/in
  samples/docker_wrapper/test_mount/job_mount.toml
  samples/docker_wrapper/test_mount/main.sh
  samples/docker_wrapper/test_mount/worker
  samples/docker_wrapper/toml.h
  samples/wsl_wrapper/wsl_wrapper.cpp
  sched/plan_class_spec.h
  sched/sched_types.cpp
  sched/sched_types.h
  win_build/boinc.sln
  win_build/docker_wrapper.vcxproj
Labels: C: Client, C: Server, PR: Enhancement, C: Library, C: Apps - WslWrapper, C: Apps - DockerWrapper

#5856 Build docker_wrapper for linux on ci and upload it to the artifacts
  deploy/prepare_deployment.py
  samples/Makefile.am
  samples/docker_wrapper/Makefile
  samples/docker_wrapper/docker_wrapper.cpp
Labels: C: Build System, PR: Bugfix, C: Apps - DockerWrapper, OS: Linux, OS: Windows

#5858 [ci] update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/android.yml
  .github/workflows/check_custom_vcpkg_ports.yml
  .github/workflows/coverity.yml
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/source-code-check.yml
  .github/workflows/test-report.yml
  .github/workflows/update_actions.yml
  .github/workflows/update_copyright_year.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#5860 client: disable debugging code
  client/app_test.cpp
  lib/util.cpp
Labels: C: Client, PR: Bugfix

#5863 fclose() -> pclose()
  lib/util.cpp
Labels: C: Client, P: Minor, PR: Bugfix

#5864 Revised heartbeat check
  samples/vboxwrapper/vboxwrapper.cpp
Labels: P: Minor, C: Apps - VboxWrapper, PR: Bugfix

#5865 Extend support for WSL and Docker apps
  client/client_state.cpp
  client/hostinfo_win.cpp
  client/hostinfo_wsl.cpp
  client/log_flags.cpp
  lib/cc_config.cpp
  lib/cc_config.h
  lib/hostinfo.h
  lib/util.cpp
  lib/util.h
  lib/wslinfo.cpp
  lib/wslinfo.h
  samples/wsl_wrapper/wsl_wrapper.cpp
  sched/plan_class_spec.cpp
  sched/plan_class_spec.h
  sched/sched_types.cpp
  sched/sched_types.h
Labels: C: Client, C: Server - Scheduler, PR: Enhancement, C: Library, C: Apps - WslWrapper

#5866 Heartbeat checks deal with time leaps
  samples/vboxwrapper/vboxwrapper.cpp
Labels: P: Minor, C: Apps - VboxWrapper, PR: Bugfix

#5868 web: parse gd version number correctly
  html/inc/profile.inc
Labels: C: Web - Project, PR: Bugfix

#5870 client/API/docker_wrapper: get CPU and mem usage of Docker apps
  api/boinc_api.cpp
  api/boinc_api.h
  client/app.cpp
  client/app.h
  client/app_control.cpp
  client/app_test.cpp
  samples/docker_wrapper/docker_wrapper.cpp
  samples/docker_wrapper/test_copy/infile
  samples/vboxwrapper/vbox_common.cpp
  samples/vboxwrapper/vboxwrapper.cpp
Labels: C: Client, PR: Enhancement, C: Apps - VboxWrapper, C: Apps - DockerWrapper

#5867 client: measure CPU time of VBox apps correctly
  client/app.cpp
  lib/procinfo.cpp
  lib/procinfo.h
Labels: C: Client, PR: Bugfix, PR: Fix required

#5872 [linux] Add Fedora 41 package
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/rpmrepo/package_depends.sh
  .github/workflows/rpmrepo/package_filelist.sh
Labels: PR: Enhancement, C: Build System, OS: Linux
