Repository BOINC/boinc, pull requests merged in 2025-09, with the labels that each got.

#6534 web: add script to remind users to retire batches, and eventually retire them
  gl
  html/inc/submit_util.inc
  html/ops/submit_retire.php
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6546 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6547 [windows] Fix signing of Windows artifacts by updating the version of installed Windows SDK.
  configure.ac
  version.h
  win_build/boinc_signing.targets
  win_build/docker_wrapper.vcxproj
Labels: C: Build System, PR: Bugfix, C: Apps - DockerWrapper, OS: Windows

#6548 [lib] fix build on mingw 10
  lib/hostinfo.cpp
Labels: C: Library, PR: Bugfix

#6529 Client, docker_wrapper (Mac): debug BUDA
  client/app_test.cpp
  client/hostinfo_unix.cpp
  configure.ac
  lib/util.cpp
  samples/docker_wrapper/docker_wrapper.cpp
  version.h
  win_build/docker_wrapper.vcxproj
Labels: C: Client, PR: Bugfix, C: Apps - DockerWrapper, OS: MacOs

#6556 client: if there's a new BOINC WSL distro, link to correct page
  client/hostinfo_wsl.cpp
Labels: C: Client, PR: Enhancement, OS: Windows

#6558 web (job submission): make output file download more secure
  html/user/get_output3.php
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6551 BUDA: support ARM hosts, and revamp architecture
  .github/workflows/linux.yml
  configure.ac
  html/inc/buda.inc
  html/inc/sandbox.inc
  html/user/all_news.php
  html/user/buda.php
  html/user/buda_submit.php
  html/user/show_apps.php
  html/user/submit.php
  lib/Makefile.linux
  lib/filesys.cpp
  sched/Makefile.am
  sched/Makefile.linux
  sched/buda.cpp
  sched/buda.h
  sched/handle_request.cpp
  sched/plan_class_spec.cpp
  sched/plan_class_spec.h
  sched/sched_array.cpp
  sched/sched_assign.cpp
  sched/sched_customize.cpp
  sched/sched_customize.h
  sched/sched_locality.cpp
  sched/sched_main.cpp
  sched/sched_nci.cpp
  sched/sched_resend.cpp
  sched/sched_score.cpp
  sched/sched_score.h
  sched/sched_send.cpp
  sched/sched_send.h
  sched/sched_shmem.cpp
  sched/sched_version.cpp
Labels: C: Server, C: Server - Scheduler, PR: Enhancement, C: Library

#6560 web (job submission): 'only own computers' fixes
  html/user/buda_submit.php
  html/user/submit.php
Labels: C: Web - Project, PR: Bugfix

#6561 [coverity] fix build
  .github/workflows/coverity.yml
Labels: C: Build System, PR: Bugfix

#6571 [linux][ci] skip 'publish package' step earlier if no actual publish gonna happen
  .github/workflows/linux-package.yml
Labels: PR: Enhancement, C: Build System, OS: Linux

#6573 [installer][windows] fix warnings
  installer/installer_setup/main.cpp
Labels: PR: Bugfix, OS: Windows, C: Installer

#6575 [ci] update actions
  .github/workflows/coverity.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6580 [ci] improve linux package builds by putting autoconf into cache
  .github/workflows/linux-package.yml
Labels: PR: Enhancement, C: Build System, OS: Linux
