Repository BOINC/boinc, pull requests merged in 2025-03, with the labels that each got.

#6130 [ci] update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/android.yml
  .github/workflows/coverity.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/test-report.yml
  .github/workflows/update_copyright_year.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6132 Replace getcwd() with boinc_getcwd()
  samples/vboxwrapper/vboxwrapper.cpp
Labels: PR: Enhancement, C: Apps - VboxWrapper

#6140 scheduler: update parsing of host info.
  db/boinc_db_types.h
  sched/sched_types.cpp
Labels: C: Server - Scheduler, PR: Bugfix

#6139 Remove unused files and variables
  samples/vboxwrapper/gbac.cpp
  samples/vboxwrapper/gbac.h
  samples/vboxwrapper/vboxjob.cpp
  samples/vboxwrapper/vboxjob.h
  samples/vboxwrapper/vboxwrapper_win.aps
Labels: PR: Enhancement, C: Apps - VboxWrapper

#6143 [ci] update actions
  .github/workflows/all_projects_list_xml_update.yml
  .github/workflows/update_copyright_year.yml
Labels: PR: Enhancement, C: Build System

#6144 debug BUDA on Unix
  client/client_types.cpp
  html/user/buda.php
  lib/hostinfo.cpp
Labels: C: Client, C: Server, C: Library, PR: Bugfix

#6137 docker_wrapper: add 'mount' and 'portmap' options to job.toml
  samples/docker_wrapper/docker_wrapper.cpp
Labels: PR: Enhancement, C: Apps - DockerWrapper

#6147 docker_wrapper: support HTML graphics
  samples/docker_wrapper/Makefile
  samples/docker_wrapper/docker_wrapper.cpp
  win_build/docker_wrapper.vcxproj
Labels: PR: Enhancement, C: Apps - DockerWrapper

#6116 setup vbox profile location
  samples/vboxwrapper/vbox_common.cpp
  samples/vboxwrapper/vbox_common.h
  samples/vboxwrapper/vbox_vboxmanage.cpp
Labels: PR: Enhancement, C: Apps - VboxWrapper

#6152 Add some comments and fix compile warning. No functional changes
  lib/hostinfo.cpp
  lib/util.cpp
Labels: PR: Enhancement, C: Library

#6153 web: use symbols rather than hardwired numbers for states in DB queries
  html/inc/db_ops.inc
  html/inc/result.inc
  html/inc/submit_util.inc
  html/inc/util_ops.inc
  html/user/server_status.php
Labels: C: Web - Project, PR: Enhancement

#6154 client, Linux: don't check for podman
  client/hostinfo_unix.cpp
Labels: C: Client, PR: Bugfix, OS: Linux

#6156 web: job submission improvements
  html/user/submit.php
Labels: C: Server, PR: Enhancement

#6159 [ci] update actions
  .github/workflows/test-report.yml
Labels: PR: Enhancement, C: Build System

#6162 docker wrapper: add a couple of printfs. No functional change.
  lib/util.cpp
  samples/docker_wrapper/docker_wrapper.cpp
Labels: PR: Enhancement, C: Library, C: Apps - DockerWrapper

#6164 web: fix XSS vulnerability in submit RPC handler
  html/user/openid_login.php
  html/user/submit_rpc_handler.php
Labels: C: Web - Project, PR: Bugfix

#6165 fix DB queries
  html/ops/failure_result_summary_by_host.php
  html/ops/failure_result_summary_by_platform.php
  html/ops/pass_percentage_by_platform.php
Labels: C: Server, PR: Bugfix

#6166 client (Win): show Docker detection details
  client/hostinfo_wsl.cpp
Labels: C: Client, PR: Enhancement, OS: Windows

#6167 Fix DockerWrapper compiler warnings
  samples/docker_wrapper/docker_wrapper.cpp
Labels: PR: Enhancement, C: Apps - DockerWrapper

#6168 [linux] add boinc user to the 'docker' group if it's present
  .github/workflows/linux-package.yml
  packages/deb/postinst
Labels: PR: Enhancement, OS: Linux, C: Installer

#6169 Web: if send a PM to banished user, say they can't reply immediately
  html/inc/pm.inc
Labels: C: Web - Private Messages, PR: Enhancement

#6170 client and docker_wrapper: bug fixes
  lib/hostinfo.cpp
  lib/util.cpp
  lib/util.h
Labels: C: Library, PR: Bugfix

#6174 [windows] fix issue with the message being misleading when showing information about the failed gpu detection
  client/gpu_detect.cpp
Labels: C: Client, PR: Bugfix, OS: Windows

#6175 client: strip leading www. from master URLs
  lib/url.cpp
  sched/handle_request.cpp
Labels: C: Library, PR: Bugfix

#6179 scheduler: add docker info to host.serialnum
  sched/handle_request.cpp
Labels: C: Server - Scheduler, PR: Enhancement

#6178 client (Linux): check for podman only if BOINC data dir is not remote
  client/hostinfo_linux.cpp
  client/hostinfo_unix.cpp
  lib/hostinfo.h
Labels: C: Client, PR: Enhancement, OS: Linux

#6183 client (Linux): parse podman version if using podman-docker
  client/hostinfo_unix.cpp
Labels: C: Client, PR: Enhancement, OS: Linux

#6185 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/coverity.yml
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/test-report.yml
  .github/workflows/update_actions.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6186 client: fix bug that caused anonymous platform apps to have ncpus=0
  client/client_state.cpp
Labels: C: Client, PR: Bugfix

#6180 Mac tweaks to installer, uninstaller
  clientgui/BOINCGUIApp.cpp
  clientgui/BOINCGUIApp.h
  mac_installer/PostInstall.cpp
  mac_installer/finish_install.cpp
  mac_installer/uninstall.cpp
Labels: C: Manager, PR: Enhancement, OS: MacOs, C: Installer

#6187 [vboxwrapper] increase version to 26210
  configure.ac
  version.h
  win_build/vboxwrapper.vcxproj
Labels: PR: Enhancement, C: Apps - VboxWrapper

#6192 [docker_wrapper] add version to the filename
  configure.ac
  deploy/prepare_deployment.py
  samples/Makefile.am
  samples/docker_wrapper/Makefile
  set-dockerwrapper-version.py
  version.h
  version.h.in
  win_build/docker_wrapper.vcxproj
  win_build/htmlgfx.vcxproj
  win_build/vboxwrapper.vcxproj
  win_build/worker.vcxproj
  win_build/wrapper.vcxproj
Labels: PR: Enhancement, C: Apps - DockerWrapper

#6193 run_command(): return command output as \n-terminated lines
  lib/util.cpp
Labels: C: Library, PR: Bugfix

#6194 docker_wrapper: remove unneeded \n
  samples/docker_wrapper/docker_wrapper.cpp
Labels: PR: Bugfix, C: Apps - DockerWrapper

#6195 Mac Manager: fix response to -s or --systray argument
  clientgui/BOINCGUIApp.cpp
Labels: C: Manager, PR: Bugfix, OS: MacOs

#6198 add new 'docker_wrapper' filename to the .gitignore file
  .gitignore
Labels: C: Build System, PR: Bugfix

#6199 Ignore MacOs specific folders and files during trailing whitespace check
  ci_tools/trailing_whitespaces_check.py
Labels: C: Build System, PR: Bugfix

#6204 [snap] fix build
  3rdParty/vcpkg_ports/triplets/ci/snap-linux-amd64.cmake
Labels: C: Build System, PR: Bugfix

#6201 client, Mac: detect podman
  client/hostinfo_unix.cpp
  samples/docker_wrapper/Makefile_mac
  samples/docker_wrapper/docker_wrapper.cpp
  samples/docker_wrapper/docker_wrapper.xcodeproj/project.pbxproj
  samples/docker_wrapper/docker_wrapper.xcodeproj/xcshareddata/xcschemes/docker_wrapper.xcscheme
Labels: C: Client, PR: Enhancement, C: Apps - DockerWrapper, OS: MacOs

#6206 Mac: build docker_wrapper without providing a code signing identity
  samples/docker_wrapper/docker_wrapper.xcodeproj/project.pbxproj
Labels: C: Build System, PR: Bugfix, C: Apps - DockerWrapper

#6208 Enable docker wrapper to forward exit codes from a container to BOINC client
  samples/docker_wrapper/docker_wrapper.cpp
Labels: PR: Enhancement, C: Apps - DockerWrapper

#6209 client and docker_wrapper: get it to work on MacOS/podman
  client/client_state.cpp
  client/hostinfo_unix.cpp
  samples/docker_wrapper/docker_wrapper.cpp
Labels: C: Client, PR: Enhancement, C: Apps - DockerWrapper, OS: MacOs

#6210 web: minor fixes
  html/inc/util.inc
  html/inc/util_basic.inc
  html/user/buda.php
  html/user/sandbox.php
Labels: C: Web - Project, PR: Enhancement

#6211 docker wrapper: fix clang compile warnings; not functional change
  samples/docker_wrapper/docker_wrapper.cpp
Labels: PR: Enhancement, C: Apps - DockerWrapper

#6207 Build docker_wrapper for MacOs on CI
  .github/workflows/osx.yml
  deploy/prepare_deployment.py
  mac_build/BuildMacBOINC.sh
  mac_build/buildMacBOINC-CI.sh
  mac_build/buildMacMakefiles-CI.sh
  samples/docker_wrapper/Makefile_mac
Labels: PR: Enhancement, C: Build System, C: Apps - DockerWrapper

#6212 web: show Docker info on host pages
  html/inc/host.inc
Labels: C: Web - Project, PR: Enhancement

#6216 Add --passthrough_child arg to wrapper app
  samples/wrapper/wrapper.cpp
Labels: PR: Enhancement, C: Apps - Wrapper
