Repository BOINC/boinc, pull requests merged in 2025-01, with the labels that each got.

#5992 [ci] fix running on Ubuntu 24.04
  .github/workflows/android.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  mingw/ci_make_apps.sh
Labels: C: Build System, PR: Bugfix

#5994 [ci] Fix build running on Ubuntu 24.04
  .github/workflows/coverity.yml
  .github/workflows/debrepo/aptly.bookworm.conf
  .github/workflows/debrepo/aptly.bullseye.conf
  .github/workflows/debrepo/aptly.buster.conf
  .github/workflows/debrepo/aptly.focal.conf
  .github/workflows/debrepo/aptly.jammy.conf
  .github/workflows/debrepo/aptly.noble.conf
  .github/workflows/debrepo/repo_update.sh
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
Labels: C: Build System, PR: Bugfix

#6004 client: don't delete unrecognized stuff in projects/
  client/cs_files.cpp
Labels: C: Client, PR: Bugfix

#6002 client: on version change, show notice with link to release notes
  client/client_state.cpp
Labels: C: Client, PR: Enhancement

#5977 Revert to 'ProtectSystem=strict' in boinc-client.service and make '/tmp' writable
  client/scripts/boinc-client.service.in
  tests/linux_package_integration_tests.py
Labels: OS: Linux, C: Installer

#6005 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/mingw.yml
  .github/workflows/osx.yml
  .github/workflows/snap.yml
  .github/workflows/update_actions.yml
  .github/workflows/wasm.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6001 get_output.php: send empty file if no files to send, rather then error messages
  html/user/get_output.php
Labels: C: Server - Remote Submission, PR: Bugfix

#6011 Rename 'Protected application execution' to 'Service Install'.
  sched/handle_request.cpp
Labels: C: Server - Scheduler

#6013 client: fix bug where avg_ncpus for anonymous platform apps defaults to zero
  client/client_state.cpp
  client/client_types.cpp
  client/cs_statefile.cpp
Labels: C: Client, PR: Bugfix

#6016 vboxwrapper (Mac): fix startup failure on Mac
  samples/vboxwrapper/vbox_vboxmanage.cpp
Labels: PR: Enhancement, C: Apps - VboxWrapper

#6022 Remove OpenSSL built-in engines and add automation tests
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  lib/crypt.cpp
  lib/crypt_prog.cpp
  tests/crypt_prog_tests.py
  tests/windows_installer_integration_tests.py
Labels: PR: Enhancement, C: Library

#6024 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6026 [ci] update OpenCppCoverage to 0.9.9.0
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6027 [installer][windows] refactor strings
  installer/InstallerStrings.cpp
  installer/boinc.json
  installer/locale/en.json
Labels: PR: Enhancement, OS: Windows, C: Installer

#6029 [windows] when running installer, search for DLLs in the system directory only since the installer itself doesn't rely on any custom DLLs.
  installer/installer_setup/main.cpp
Labels: PR: Bugfix, OS: Windows, C: Installer

#6030 [windows][installer] enable 'change'\'modify' and 'repair' options.
  installer/boinc.json
Labels: PR: Enhancement, OS: Windows, C: Installer

#6031 [linux] update gdk-pixbuf custom vcpkg port
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/portfile.cmake
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/vcpkg.json
Labels: PR: Enhancement, C: Build System, OS: Linux

#6033 client and docker_wrapper: lower-case image and container names
  lib/app_ipc.cpp
  lib/str_util.h
  lib/url.cpp
  lib/util.cpp
Labels: PR: Enhancement, C: Library

#6034 crypt_prog: fix build errors
  lib/crypt_prog.cpp
Labels: C: Server, PR: Bugfix

#6036 wrapper: code cleanup; no functional change
  client/Makefile.linux
  samples/wrapper/wrapper.cpp
Labels: PR: Enhancement, C: Apps - Wrapper

#6038 mail_passwd.php: allow projects to add their own message at end of page about password reset email.
  html/user/mail_passwd.php
Labels: C: Server - Setup, PR: Enhancement

#6040 web: on forum page, tell user they have to log in to post
  html/inc/forum.inc
  html/user/forum_forum.php
  html/user/forum_post.php
Labels: C: Web, PR: Enhancement

#6041 web: in pages that take an ID as an arg, show error if not valid ID
  html/user/forum_banishment_vote.php
  html/user/forum_banishment_vote_action.php
  html/user/forum_moderate_post.php
  html/user/forum_moderate_thread.php
  html/user/forum_post.php
  html/user/forum_rate.php
  html/user/forum_reply.php
  html/user/forum_subscribe.php
  html/user/forum_thread_vote.php
  html/user/forum_user_posts.php
Labels: C: Web, PR: Enhancement

#6049 [windows] Fix installer to start BOINC unelevated.
  clientsetup/win/launcher.cpp
Labels: PR: Bugfix, OS: Windows, C: Installer
