Repository BOINC/boinc, pull requests merged in 2025-05, with the labels that each got.

#6292 BUDA: treat variants as CPU (not plan class) if 'cpu' is in variant name
  html/user/buda.php
Labels: C: Web - Project, PR: Enhancement

#6295 web: fix 'powered by BOINC' behavior in footer
  html/project.sample/project.inc
Labels: C: Web - Project, PR: Bugfix

#6287 Fix regressions in Drupal following BOINC changes
  drupal/sites/all/features/user_account_host_list/user_account_host_list.views_default.inc
  drupal/sites/all/features/work_and_host_stats/work_and_host_stats.views_default.inc
  drupal/sites/default/boinc/modules/boincuser/includes/boincuser.helpers.inc
  drupal/sites/default/boinc/modules/boincwork/includes/boincwork.forms.inc
Labels: PR: Bugfix, C: Web - Drupal

#6297 docker_wrapper: use the BOINC WSL distro if present
  lib/wslinfo.cpp
Labels: C: Client, PR: Enhancement, OS: Windows

#6298 Fix compiler warning and avoid magic number in function call
  client/hostinfo_unix.cpp
Labels: C: Client, PR: Bugfix, OS: Linux

#6300 [windows] fix windows build by building unit-tests as c++17 code due to the update of gtest.
  win_build/unittests.vcxproj
Labels: C: Build System, C: Testing, PR: Bugfix, OS: Windows

#6305 web (BUDA) add 'expected runtime' to submission form
  html/user/buda_submit.php
  html/user/job_fpops.php
Labels: C: Web - Project, PR: Enhancement

#6308 web: Remove some globals. No functional change.
  html/inc/account.inc
  html/inc/akismet.inc
  html/inc/bootstrap.inc
  html/inc/forum_email.inc
  html/inc/host.inc
  html/inc/prefs.inc
  html/inc/submit_util.inc
  html/inc/user_util.inc
  html/inc/util.inc
  html/inc/util_basic.inc
  html/user/account_ownership.php
  html/user/create_account_form.php
  html/user/create_profile.php
  html/user/download_software.php
  html/user/ffmail_form.php
  html/user/get_project_config.php
  html/user/join.php
  html/user/login_token_lookup.php
  html/user/logout.php
  html/user/register.php
  html/user/sample_index.php
  html/user/signup.php
  html/user/submit_example.php
  html/user/team_create_action.php
  html/user/validate_email_addr.php
Labels: C: Web - Project, PR: Enhancement

#6309 web: minor fixes
  html/inc/cache.inc
  html/project.sample/cache_parameters.inc
  html/user/create_team.php
  html/user/team_create_action.php
  html/user/team_create_form.php
Labels: C: Web - Project, PR: Enhancement

#6313 [linux] update gdk-pixbuf vcpkg port from upstream
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/portfile.cmake
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/vcpkg.json
Labels: C: Manager, PR: Enhancement, OS: Linux

#6315 web: fix warning if 'buda_plan_classes' doesn't exist
  html/inc/app_types.inc
Labels: C: Web - Project, PR: Bugfix

#6317 RPC-based job submission: make it work with PHP 8
  html/inc/submit.inc
Labels: C: Web - Project, PR: Bugfix

#6318 web: use 'cores' instead of 'processors'
  html/inc/host.inc
Labels: C: Web - Project, PR: Enhancement

#6321 Mac: fix small typo in error message
  client/check_security.cpp
Labels: C: Client, PR: Bugfix, OS: MacOs

#6320 web: fix DB error (newer MySQL) when add user submit permission
  html/user/manage_project.php
Labels: C: Web - Project, PR: Bugfix

#6322 add 'Final_Install-Info.plist' to the set-client-version.py script
  set-client-version.py
Labels: PR: Enhancement, C: Build System

#6323 Revert "Merge pull request #6322 from BOINC/vko_add_Final_Install-info.plist_to_the_version_update_script"
  set-client-version.py
Labels: C: Build System, PR: Bugfix, OS: MacOs

#6327 web: tweak colors in batch display to work better for white mode
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6328 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/test-report.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6329 Fix print statements in database module
  py/Boinc/database.py
Labels: C: Server, PR: Bugfix

#6335 Fix spacing after commas in Windows source files
  api/graphics2_win.cpp
  api/windows_opengl.cpp
  client/hostinfo_win.cpp
  samples/gfx_html/browserctrl_win.cpp
Labels: C: Client, P: Trivial, PR: Enhancement, C: Library, C: Apps - Samples

#6336 style: standardize if spacing
  client/hostinfo_win.cpp
Labels: C: Client, PR: Enhancement, OS: Windows

#6324 [ci] Test vcpkg port, fix includes in libboinc
  .github/workflows/vcpkg_test.yml
  client/client_msgs.h
  client/hostinfo_linux.cpp
  lib/app_ipc.cpp
  lib/common_defs.h
  lib/coproc.h
  lib/hostinfo.cpp
  lib/hostinfo.h
  lib/miofile.h
  lib/opencl_boinc.h
  lib/proxy_info.h
  lib/str_util.h
  lib/util.cpp
  lib/win_util.cpp
  tests/unit-tests/lib/test_parse.cpp
  tests/unit-tests/lib/test_str_util.cpp
  tests/vcpkg/CMakeLists.txt
  tests/vcpkg/main.cpp
  tests/vcpkg/portfilefix.py
  tests/vcpkg/ports/boinc/CMakeLists.txt
  tests/vcpkg/ports/boinc/portfile.cmake
  tests/vcpkg/ports/boinc/vcpkg.json
  tests/vcpkg/vcpkg.json
Labels: PR: Enhancement, C: Build System, C: Library, PR: Bugfix

#6339 client: make resource usages take effect after reread app_config.xml
  client/app_config.cpp
  client/client_state.cpp
  client/client_state.h
Labels: C: Client, PR: Bugfix

#6289 [ci][osx] build libboinc with cmake in parallel for x64 and arm64.
  .codecov.yml
  .github/workflows/osx.yml
  3rdParty/vcpkg_ports/configs/libs/vcpkg.json
  lib/CMakeLists.txt
  osx/ci_build_libs_cmake.sh
  tests/executeUnitTests.sh
  tests/unit-tests/CMakeLists.txt
  tests/unit-tests/lib/test_str_util.cpp
  tests/unit-tests/lib/test_util.cpp
Labels: PR: Enhancement, C: Build System, OS: MacOs

#6341 web: on page that shows apps, show register/apply buttons
  html/user/show_apps.php
Labels: C: Web - Project, PR: Enhancement

#6343 client: remove spurious error messages about WU FLOPS
  client/client_types.cpp
  client/client_types.h
Labels: C: Client, PR: Bugfix

#6345 web: fix recaptcha bug
  html/inc/recaptchalib.inc
  html/inc/user_util.inc
  html/user/account_ownership.php
  html/user/create_account_form.php
  html/user/create_profile.php
  html/user/register.php
  html/user/signup.php
  html/user/team_create_action.php
  html/user/team_create_form.php
Labels: C: Web - Project, PR: Bugfix

#6338 Web, scheduler: support keyword prefs on BOINC projects
  html/inc/kw_prefs.inc
  html/inc/user.inc
  html/user/buda.php
  html/user/buda_submit.php
  html/user/kw_prefs.php
  html/user/manage_project.php
  html/user/workunit.php
  lib/keyword.cpp
  sched/sched_keyword.cpp
  sched/sched_keyword.h
  sched/sched_score.cpp
  sched/sched_send.cpp
  sched/sched_shmem.cpp
  tools/create_work.cpp
Labels: C: Client, C: Server, C: Web - Project, PR: Enhancement

#6352 remove unnecessary includes. No functional change
  api/boinc_api.h
  lib/app_ipc.h
  lib/common_defs.h
Labels: P: Trivial, PR: Enhancement, C: Library

#6353 docker_wrapper: read fraction done from a file and report to client
  samples/docker_wrapper/docker_wrapper.cpp
  samples/worker/worker.cpp
Labels: PR: Enhancement, C: Apps - DockerWrapper

#6355 API: fix C app build errors
  api/boinc_api.cpp
  api/boinc_api.h
  clientgui/sg_ProjectPanel.cpp
  clientgui/sg_TaskPanel.cpp
  clientscr/gfx_switcher.cpp
  clientscr/screensaver_x11.cpp
  clientscr/ss_app.cpp
  lib/app_ipc.cpp
  lib/app_ipc.h
  lib/common_defs.h
  samples/wrapper/wrapper.cpp
  tests/vcpkg/CMakeLists.txt
  tests/vcpkg/main.c
Labels: C: Library, PR: Bugfix
