Repository BOINC/boinc, pull requests merged in 2025-07, with the labels that each got.

#6413 [ci] fix linux package build pipeline
  .github/workflows/linux-package.yml
Labels: C: Build System, PR: Bugfix

#6417 [ci] fix linux package release ci pipeline
  .github/workflows/linux-package-stable-release.yml
Labels: C: Build System, PR: Bugfix

#6418 web (job submission): enhancements
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6424 web: show amount of computing in batch job list
  html/user/site_search.php
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6423 docker_wrapper (Mac/Linux): show appropriate error message if Docker not present
  lib/hostinfo.cpp
  samples/docker_wrapper/docker_wrapper.cpp
Labels: PR: Enhancement, C: Library, C: Apps - DockerWrapper

#6425 client (Mac): fix Podman detection (must escape spaces in env args)
  lib/hostinfo.cpp
Labels: C: Library, PR: Bugfix, OS: MacOs

#6426 web (job submission): add commands for showing hosts that worked on batch
  html/inc/host.inc
  html/user/submit.php
  html/user/submit_stats.php
Labels: C: Web - Project, PR: Enhancement

#6427 [linux] enable 'update-from-stable' tests for Fedora 41/42. Change stable version from 8.2.1 to 8.2.4
  .github/workflows/linux-package.yml
Labels: PR: Enhancement, C: Build System, OS: Linux

#6430 [ci] fix debian buster sources.list
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
Labels: C: Build System, PR: Bugfix

#6429 web: remove Vbox stuff from download page; fix button appearance
  html/inc/forum.inc
  html/inc/web_rpc_api.inc
  html/user/download_software.php
Labels: C: Web - Project, PR: Enhancement

#6432 [ci] update actions
  .github/workflows/test-report.yml
Labels: PR: Enhancement, C: Build System

#6431 [linux][apps][arm64] Add arm64 linux with vcpkg
  .github/workflows/linux.yml
  deploy/prepare_deployment.py
  linux/arm64/ci_configure_apps.sh
  linux/arm64/ci_configure_libs.sh
  linux/arm64/update_vcpkg_apps.sh
  linux/arm64/update_vcpkg_libs.sh
  samples/openclapp/Makefile
  samples/openclapp/Makefile_AMD
  samples/openclapp/Makefile_NVIDIA
Labels: C: Build System, PR: Bugfix

#6434 [ci] update set-client-version.py to target correct json file of the Windows installer configuration
  release_tools/set-client-version.py
Labels: C: Build System, PR: Bugfix

#6437 [ci] improve linux package fedora tests
  .github/workflows/linux-package.yml
Labels: PR: Enhancement, C: Build System

#6446 Remove unfinished wasm compilation support.
  .github/workflows/wasm.yml
  .gitignore
  3rdParty/vcpkg_ports/configs/client/wasm/vcpkg.json
  3rdParty/vcpkg_ports/triplets/ci/wasm32-emscripten.cmake
  Makefile.am
  client/hostinfo_network.cpp
  client/hostinfo_unix.cpp
  configure.ac
  deploy/prepare_deployment.py
  samples/wasm/index.html
  wasm/ci_configure_client.sh
  wasm/ci_make.sh
  wasm/update_emsdk.sh
  wasm/update_emsdk_vcpkg.sh
Labels: C: Build System, PR: Cleanup/Refactoring

#6448 Web: job submit enhancements
  html/inc/keywords.inc
  html/inc/submit_db.inc
  html/inc/submit_util.inc
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6453 [ci] Fix mingw build
  .github/workflows/mingw.yml
Labels: C: Build System, PR: Bugfix

#6452 web (job submission): enumerate and order batches correctly
  html/inc/bootstrap.inc
  html/user/submit.php
Labels: C: Web - Project, PR: Bugfix

#6457 web (job submission): fix bug in retire batch
  html/inc/submit_util.inc
Labels: C: Web - Project, PR: Bugfix

#6460 MacOS 26 Screensaver fixes
  client/check_security.cpp
  client/switcher.cpp
  clientgui/mac/templates/Finish_Install-Info.plist
  clientgui/mac/templates/PostInstall-Info.plist
  clientgui/mac/templates/ScreenSaver-Info.plist
  clientscr/Mac_Saver_Module.h
  clientscr/Mac_Saver_ModuleView.h
  clientscr/Mac_Saver_ModuleView.m
  clientscr/gfx_cleanup.mm
  clientscr/gfx_switcher.cpp
  clientscr/mac_saver_module.cpp
  clientscr/screensaver.cpp
  mac_build/boinc.xcodeproj/project.pbxproj
  mac_build/boinc.xcodeproj/xcshareddata/xcschemes/boinc_finish_install.xcscheme
  mac_installer/PostInstall.cpp
  mac_installer/finish_install.cpp
  mac_installer/release_boinc.sh
  mac_installer/release_brand.sh
Labels: C: Client, C: Screen Saver, PR: Bugfix, OS: MacOs, C: Installer

#6463 [ci][android] build vcpkg test on r23c and r27c NDKs
  .github/workflows/vcpkg_test.yml
  configure.ac
  lib/diagnostics.cpp
Labels: C: Library, PR: Bugfix, OS: Android
