Repository BOINC/boinc, pull requests merged in 2025-04, with the labels that each got.

#6218 wrapper: code cleanup; no functional change
  samples/wrapper/wrapper.cpp
Labels: PR: Enhancement, C: Apps - Wrapper

#6220 Workflow: Set RELEASE_ARCH for arm64 build non-release
  .github/workflows/linux.yml
Labels: C: Build System, PR: Bugfix, C: Apps - Samples, OS: Linux

#6222 Web: Sandbox and job submission fixes (mostly for BUDA)
  html/inc/bootstrap.inc
  html/user/buda.php
  html/user/buda_submit.php
  html/user/get_output3.php
  html/user/sandbox.php
Labels: C: Web - Project, PR: Enhancement

#6224 Add custom vcpkg ports to test the fix
  3rdParty/vcpkg_ports/ports/ftgl/02_enable-cpp11-std.patch
  3rdParty/vcpkg_ports/ports/ftgl/fix-cmake.diff
  3rdParty/vcpkg_ports/ports/ftgl/fix-gl-flags.diff
  3rdParty/vcpkg_ports/ports/ftgl/freetype-usage.diff
  3rdParty/vcpkg_ports/ports/ftgl/install-pkgconfig.diff
  3rdParty/vcpkg_ports/ports/ftgl/portfile.cmake
  3rdParty/vcpkg_ports/ports/ftgl/vcpkg.json
  3rdParty/vcpkg_ports/ports/libuuid/CMakeLists.txt
  3rdParty/vcpkg_ports/ports/libuuid/config.linux.h
  3rdParty/vcpkg_ports/ports/libuuid/portfile.cmake
  3rdParty/vcpkg_ports/ports/libuuid/unofficial-libuuid-config.cmake.in
  3rdParty/vcpkg_ports/ports/libuuid/vcpkg.json
  3rdParty/vcpkg_ports/ports/wxwidgets/example/CMakeLists.txt
  3rdParty/vcpkg_ports/ports/wxwidgets/fix-libs-export.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/fix-pcre2.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/gtk3-link-libraries.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/install-layout.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/nanosvg-ext-depend.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/portfile.cmake
  3rdParty/vcpkg_ports/ports/wxwidgets/relocatable-wx-config.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/sdl2.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/setup.h.in
  3rdParty/vcpkg_ports/ports/wxwidgets/usage
  3rdParty/vcpkg_ports/ports/wxwidgets/vcpkg-cmake-wrapper.cmake
  3rdParty/vcpkg_ports/ports/wxwidgets/vcpkg.json
  3rdParty/vcpkg_ports/triplets/ci/snap-linux-amd64.cmake
  tests/unit-tests/CMakeLists.txt
Labels: C: Build System, PR: Bugfix

#6223 scheduler: bug fixes for docker plan class
  sched/plan_class_spec.cpp
  sched/sched_send.cpp
Labels: C: Server - Scheduler, PR: Enhancement

#6228 web: use 'you' rather than user name in other-projects list for logged-in user
  client/hostinfo_wsl.cpp
  html/user/show_user.php
Labels: C: Web - Project, PR: Enhancement

#6227 web: declare $config global (for Drupal)
  html/inc/util.inc
Labels: C: Web - Project, PR: Enhancement

#6229 client: if no Docker, display event and notice with installation instructions
  client/client_state.cpp
  lib/hostinfo.cpp
  lib/hostinfo.h
Labels: C: Client, PR: Enhancement, C: Library

#6230 [ci] remove custom vcpkg ports that were updated upstream
  3rdParty/vcpkg_ports/ports/ftgl/02_enable-cpp11-std.patch
  3rdParty/vcpkg_ports/ports/ftgl/fix-cmake.diff
  3rdParty/vcpkg_ports/ports/ftgl/fix-gl-flags.diff
  3rdParty/vcpkg_ports/ports/ftgl/freetype-usage.diff
  3rdParty/vcpkg_ports/ports/ftgl/install-pkgconfig.diff
  3rdParty/vcpkg_ports/ports/ftgl/portfile.cmake
  3rdParty/vcpkg_ports/ports/ftgl/vcpkg.json
  3rdParty/vcpkg_ports/ports/libuuid/CMakeLists.txt
  3rdParty/vcpkg_ports/ports/libuuid/config.linux.h
  3rdParty/vcpkg_ports/ports/libuuid/portfile.cmake
  3rdParty/vcpkg_ports/ports/libuuid/unofficial-libuuid-config.cmake.in
  3rdParty/vcpkg_ports/ports/libuuid/vcpkg.json
Labels: PR: Enhancement, C: Build System

#6231 Web: improve appearance of BUDA interface. No changes in functionality.
  html/user/buda.php
  html/user/buda_submit.php
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6232 Remove libatomic reference in linux aarch64 build
  linux/arm64/build_curl_arm64.sh
  linux/arm64/build_example_arm64.sh
  linux/arm64/build_openssl_arm64.sh
Labels: PR: Enhancement, C: Build System, OS: Linux

#6233 web: fix job submission admin page
  html/inc/bootstrap.inc
  html/inc/util.inc
  html/user/manage_project.php
Labels: C: Web - Project, PR: Bugfix

#6237 [ci] remove custom wxwidgets vcpkg port
  3rdParty/vcpkg_ports/ports/wxwidgets/example/CMakeLists.txt
  3rdParty/vcpkg_ports/ports/wxwidgets/fix-libs-export.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/fix-pcre2.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/gtk3-link-libraries.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/install-layout.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/nanosvg-ext-depend.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/portfile.cmake
  3rdParty/vcpkg_ports/ports/wxwidgets/relocatable-wx-config.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/sdl2.patch
  3rdParty/vcpkg_ports/ports/wxwidgets/setup.h.in
  3rdParty/vcpkg_ports/ports/wxwidgets/usage
  3rdParty/vcpkg_ports/ports/wxwidgets/vcpkg-cmake-wrapper.cmake
  3rdParty/vcpkg_ports/ports/wxwidgets/vcpkg.json
Labels: PR: Enhancement, C: Build System

#6239 web: use select2 for app file selection in BUDA
  html/inc/bootstrap.inc
  html/user/buda.php
  html/user/custom_dark.css
Labels: C: Web - Project, PR: Bugfix

#6240 Update lib/Makefile.mingw
  lib/Makefile.mingw
Labels: C: Build System, PR: Bugfix

#6243 Update client version to 8.3.0
  android/BOINC/app/build.gradle
  configure.ac
  installer/boinc.json
  snap/gui/boinc.desktop
  snap/snapcraft.yaml
  version.h
Labels: PR: Enhancement, C: Installer

#6244 fix set-client-version.py script that previously ignored setting release version for Android
  set-client-version.py
Labels: PR: Bugfix, OS: Android, C: Installer

#6245 Fix snprintf() errors introduced in PR #4864
  client/mac_address.cpp
  lib/unix_util.cpp
Labels: C: Client, PR: Bugfix, OS: MacOs

#6249 [ci] update actions
  .github/workflows/android.yml
Labels: PR: Enhancement, C: Build System

#6250 web: improve job submission interface
  html/inc/bootstrap.inc
  html/user/buda.php
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6251 [ci][linux] add fedora 42 to the build pipeline
  .github/workflows/linux-package-stable-release.yml
  .github/workflows/linux-package.yml
  .github/workflows/rpmrepo/package_depends.sh
  .github/workflows/rpmrepo/package_filelist.sh
  .github/workflows/rpmrepo/repo_update.sh
Labels: PR: Enhancement, C: Build System, OS: Linux

#6253 win build: fix typo in docker_wrapper project file
  configure.ac
  version.h
  win_build/docker_wrapper.vcxproj
Labels: PR: Bugfix, C: Apps - DockerWrapper

#6254 web (job submission): big fixes and enhancements
  html/inc/bootstrap.inc
  html/inc/submit_util.inc
  html/user/buda.php
  html/user/buda_submit.php
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6255 submit_buda: make it work again
  tools/submit_buda
Labels: PR: Enhancement, C: Server - Remote Submission

#6257 docker_wrapper: show details if graphics host port allocation fails
  lib/network.cpp
  samples/docker_wrapper/docker_wrapper.cpp
Labels: PR: Enhancement, C: Apps - DockerWrapper

#6256 update_versions: don't require that API_VERSION is at start of string.
  tools/update_versions
Labels: C: Server, PR: Bugfix

#6261 web (job submission): various tweaks
  html/inc/result.inc
  html/inc/submit_util.inc
  html/project.sample/project.inc
  html/user/buda.php
  html/user/submit.php
  tools/project.xml
Labels: C: Web - Project, PR: Enhancement

#6263 client (linux): verify docker/podman detection by running hello world image
  client/hostinfo_unix.cpp
Labels: C: Client, PR: Enhancement

#6266 [ci] enable 'upgrade from alpha' tests for Fedora 41 and 42
  .github/workflows/linux-package.yml
Labels: PR: Enhancement, C: Build System

#6267 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6272 web: web-based job submission changes
  html/inc/bootstrap.inc
  html/inc/buda.inc
  html/inc/keywords.inc
  html/user/buda.php
  html/user/show_apps.php
  html/user/submit.php
Labels: C: Web - Project, PR: Enhancement

#6275 [linux] fix packages to work with podman/docker properly.
  .github/workflows/linux-package.yml
  client/hostinfo_unix.cpp
  client/scripts/boinc-client.service.in
  packages/deb/postinst
  tests/linux_package_integration_tests.py
Labels: C: Client, PR: Bugfix, OS: Linux, C: Installer

#6276 web (job submission) additions
  html/inc/keywords.inc
  html/user/show_apps.php
Labels: C: Web - Project, PR: Enhancement

#6277 web: add debugging code for [code]/[pre] expansion problem
  html/inc/text_transform.inc
Labels: C: Web - Forums, PR: Bugfix

#6278 Various BUDA-related bugs and enhancements
  client/client_types.cpp
  client/client_types.h
  clientgui/ViewWork.cpp
  html/user/buda_submit.php
  lib/gui_rpc_client.h
  lib/gui_rpc_client_ops.cpp
  samples/docker_wrapper/docker_wrapper.cpp
  tools/backend_lib.cpp
  tools/create_work.cpp
Labels: C: Client, C: Manager, C: Web - Project, PR: Enhancement, C: Apps - DockerWrapper

#6280 [linux] change 'upgrade-from-alpha' fedora test from 8.2.1 to 8.2.2
  .github/workflows/linux-package.yml
Labels: PR: Enhancement, C: Build System

#6281 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux-package.yml
  .github/workflows/test-report.yml
Labels: PR: Enhancement, C: Build System

#6282 Replace egrep
  configure.ac
  m4/ax_check_glut.m4
  m4/boinc_gtk.m4
  samples/nvcuda/common.mk
  samples/nvcuda/common_mac.mk
  tools/check_project
  tools/update_versions
  tools/update_versions_v6
Labels: C: Server, PR: Enhancement, C: Build System

#6284 Various improvements to web-based job submission and app management
  html/inc/boinc_db.inc
  html/inc/bootstrap.inc
  html/inc/submit_util.inc
  html/user/buda.php
  html/user/buda_submit.php
  html/user/manage_app.php
  html/user/manage_project.php
  html/user/submit.php
  html/user/submit_example.php
Labels: C: Web - Project, PR: Enhancement

#6285 BUDA: add 'max runtime' param for job submission
  html/user/buda_submit.php
Labels: C: Web - Project, PR: Enhancement

#6286 [linux] update gdk-pixbuf from the vcpkg upstream
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/portfile.cmake
  3rdParty/vcpkg_ports/ports/gdk-pixbuf/vcpkg.json
Labels: C: Manager, PR: Enhancement, C: Build System, OS: Linux

#6288 web: job submission enhancements
  html/inc/boinc_db.inc
  html/user/buda_submit.php
  html/user/get_output2.php
  html/user/get_output3.php
  html/user/submit.php
  html/user/workunit.php
Labels: C: Web - Project, PR: Enhancement
