Repository BOINC/boinc, pull requests merged in 2025-08, with the labels that each got.

#6467 Remove unused variables. Switch boincmgr.vcxproj to use wxWidgets 3.3.*.
  clientgui/AdvancedFrame.cpp
  win_build/boincmgr.vcxproj
Labels: C: Build System, PR: Bugfix, OS: Linux, OS: Windows, OS: Linux - snapcraft

#6469 [ci][osx] Add 'Run_Podman' to artifacts
  deploy/prepare_deployment.py
Labels: PR: Enhancement, C: Build System, OS: MacOs

#6475 [ci][windows] split msbuild and cmake builds, add debug builds
  .github/workflows/windows.yml
  3rdParty/vcpkg_ports/triplets/ci/arm64-windows-static.cmake
  3rdParty/vcpkg_ports/triplets/ci/x64-windows-static.cmake
Labels: PR: Enhancement, C: Build System, OS: Windows

#6480 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/coverity.yml
  .github/workflows/linux-package.yml
  .github/workflows/linux.yml
  .github/workflows/osx.yml
  .github/workflows/test-report.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6487 web: make sure News forum is valid
  html/inc/news.inc
Labels: C: Web - Project, PR: Bugfix

#6493 Fix trailing whitespace
  client/hostinfo_unix.cpp
Labels: C: Build System, PR: Bugfix

#6505 Fix .gitignore file to include uppercase and multi_thread sample applications together with the vim temporary files.
  .gitignore
Labels: C: Build System, PR: Bugfix

#6502 Client, Manager: show project files as correct size, not 0
  client/pers_file_xfer.cpp
  clientgui/ViewTransfers.cpp
Labels: C: Client, C: Manager, PR: Bugfix

#6515 [ci] update actions
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System

#6517 client (Mac): count the VM used by Podman as BOINC CPU time
  lib/procinfo.cpp
Labels: C: Client, PR: Enhancement, OS: MacOs

#6522 client, Mac: fix typo in VM name
  lib/procinfo.cpp
Labels: C: Client, PR: Bugfix, OS: MacOs

#6512 client (win): if boinc-buda-runner WSL distro is present, ignore others
  client/hostinfo_wsl.cpp
Labels: C: Client, PR: Enhancement, OS: Windows

#6528 [ci] update libwebp vcpkg custom port
  3rdParty/vcpkg_ports/ports/libwebp/vcpkg.json
Labels: C: Build System, PR: Bugfix

#6530 Remove some minor warnings
  clientgui/AdvancedFrame.cpp
  clientgui/BOINCBaseFrame.cpp
  clientgui/BOINCGUIApp.cpp
  clientgui/BOINCListCtrl.cpp
  clientgui/BOINCTaskBar.cpp
  clientgui/BOINCTaskBar.h
  clientgui/DlgAdvPreferencesBase.cpp
  clientgui/DlgGenericMessage.h
  clientgui/MainDocument.cpp
  clientgui/ViewProjects.cpp
  clientgui/ViewTransfers.cpp
  clientgui/ViewWork.cpp
  clientgui/sg_BoincSimpleFrame.cpp
  clientgui/sg_DlgPreferences.cpp
Labels: C: Manager, PR: Enhancement

#6532 [ci] use windows-latest everywhere in the windows build workflows (prepared for the windows-2025 image migration)
  .github/workflows/windows.yml
Labels: PR: Enhancement, C: Build System
